// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod aliases_v1_alias_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::aliases::v1::*;

    impl temporal_runtime::TemporalProtoMessage for RunInput {
        const MESSAGE_TYPE: &'static str = "aliases.v1.RunInput";
    }
    impl temporal_runtime::TemporalProtoMessage for RunOutput {
        const MESSAGE_TYPE: &'static str = "aliases.v1.RunOutput";
    }

    pub const RUN_WORKFLOW_NAME: &str = "aliases.v1.AliasService.Run";
    pub const RUN_TASK_QUEUE: &str = "aliases";
    pub const RUN_WORKFLOW_ALIASES: &[&str] = &["aliases.v1.AliasService.RunLegacy", "aliases.v1.AliasService.RunV0"];

    pub struct AliasServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl AliasServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `aliases.v1.AliasService.Run` workflow.
        pub async fn run(
            &self,
            input: RunInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "aliases".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `aliases.v1.AliasService.Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<RunOutput> {
            temporal_runtime::wait_result_proto::<RunOutput>(&self.inner).await
        }

    }

}
