// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod full_v1_full_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::full::v1::*;

    pub const RUN_WORKFLOW_NAME: &str = "full.v1.FullService/Run";
    pub const RUN_TASK_QUEUE: &str = "full";

    pub struct FullServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl FullServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `full.v1.FullService/Run` workflow.
        pub async fn run(
            &self,
            input: RunInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::eval_id_expression("run-{{ .Name }}")
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                opts.id_reuse_policy,
                opts.execution_timeout,
                opts.run_timeout,
                opts.task_timeout,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `full.v1.FullService/Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
    }

    impl RunStartOptions {
        pub fn default_id_reuse_policy() -> temporal_runtime::WorkflowIdReusePolicy {
            temporal_runtime::WorkflowIdReusePolicy::AllowDuplicateFailedOnly
        }
        pub fn default_execution_timeout() -> Duration {
            Duration::from_secs(7200)
        }
        pub fn default_run_timeout() -> Duration {
            Duration::from_secs(3600)
        }
        pub fn default_task_timeout() -> Duration {
            Duration::from_secs(60)
        }
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<RunOutput> {
            temporal_runtime::wait_result_proto::<RunOutput>(&self.inner).await
        }

        /// Send the `Cancel` signal.
        pub async fn cancel(&self, input: CancelInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "Cancel", &input).await
        }

        /// Send the `Bootstrap` signal.
        pub async fn bootstrap(&self, input: BootstrapInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "Bootstrap", &input).await
        }

        /// Run the `Status` query.
        pub async fn status(&self) -> Result<StatusOutput> {
            temporal_runtime::query_proto_empty::<StatusOutput>(&self.inner, "Status").await
        }

        /// Run the `Reconfigure` update.
        pub async fn reconfigure(&self, input: ReconfigureInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<ReconfigureOutput> {
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&self.inner, "Reconfigure", &input, wait_policy).await
        }

    }

    /// Start `full.v1.FullService/Run` and atomically deliver the `Bootstrap` signal.
    pub async fn bootstrap_with_start(
        client: &temporal_runtime::TemporalClient,
        signal_input: BootstrapInput,
        workflow_input: RunInput,
        opts: RunStartOptions,
    ) -> Result<RunHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            temporal_runtime::eval_id_expression("run-{{ .Name }}")
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
        let inner = temporal_runtime::signal_with_start_workflow_proto(
            client,
            RUN_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "Bootstrap",
            &signal_input,
            opts.id_reuse_policy,
            opts.execution_timeout,
            opts.run_timeout,
            opts.task_timeout,
        ).await?;
        Ok(RunHandle { inner })
    }

    /// Start `full.v1.FullService/Run` and atomically deliver the `Reconfigure` update.
    pub async fn reconfigure_with_start(
        client: &temporal_runtime::TemporalClient,
        update_input: ReconfigureInput,
        workflow_input: RunInput,
        opts: RunStartOptions,
        wait_policy: temporal_runtime::WaitPolicy,
    ) -> Result<(RunHandle, ReconfigureOutput)> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            temporal_runtime::eval_id_expression("run-{{ .Name }}")
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
        let (inner, update_result) = temporal_runtime::update_with_start_workflow_proto::<ReconfigureInput, ReconfigureOutput>(
            client,
            RUN_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "Reconfigure",
            &update_input,
            wait_policy,
            opts.id_reuse_policy,
            opts.execution_timeout,
            opts.run_timeout,
            opts.task_timeout,
        ).await?;
        Ok((RunHandle { inner }, update_result))
    }

}
