// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod full_v1_full_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::full::v1::*;

    impl temporal_runtime::TemporalProtoMessage for BootstrapInput {
        const MESSAGE_TYPE: &'static str = "full.v1.BootstrapInput";
    }
    impl temporal_runtime::TemporalProtoMessage for CancelInput {
        const MESSAGE_TYPE: &'static str = "full.v1.CancelInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureInput {
        const MESSAGE_TYPE: &'static str = "full.v1.ReconfigureInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureOutput {
        const MESSAGE_TYPE: &'static str = "full.v1.ReconfigureOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for RunInput {
        const MESSAGE_TYPE: &'static str = "full.v1.RunInput";
    }
    impl temporal_runtime::TemporalProtoMessage for RunOutput {
        const MESSAGE_TYPE: &'static str = "full.v1.RunOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for StatusOutput {
        const MESSAGE_TYPE: &'static str = "full.v1.StatusOutput";
    }

    pub const RUN_WORKFLOW_NAME: &str = "full.v1.FullService.Run";
    pub const RUN_TASK_QUEUE: &str = "full";

    fn run_id(input: &RunInput) -> String {
        format!("run-{}", input.name)
    }

    pub struct FullServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl FullServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `full.v1.FullService.Run` workflow.
        pub async fn run(
            &self,
            input: RunInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
            let id_reuse_policy = opts.id_reuse_policy.or(Some(temporal_runtime::WorkflowIdReusePolicy::AllowDuplicateFailedOnly));
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout.or(Some(Duration::from_secs(7200)));
            let run_timeout = opts.run_timeout.or(Some(Duration::from_secs(3600)));
            let task_timeout = opts.task_timeout.or(Some(Duration::from_secs(60)));
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `full.v1.FullService.Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl RunStartOptions {
        pub fn default_id_reuse_policy() -> temporal_runtime::WorkflowIdReusePolicy {
            temporal_runtime::WorkflowIdReusePolicy::AllowDuplicateFailedOnly
        }
        pub fn default_execution_timeout() -> Duration {
            Duration::from_secs(7200)
        }
        pub fn default_run_timeout() -> Duration {
            Duration::from_secs(3600)
        }
        pub fn default_task_timeout() -> Duration {
            Duration::from_secs(60)
        }
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<RunOutput> {
            temporal_runtime::wait_result_proto::<RunOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

        /// Send the `full.v1.FullService.Cancel` signal.
        pub async fn cancel(&self, input: CancelInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "full.v1.FullService.Cancel", &input).await
        }

        /// Send the `full.v1.FullService.Bootstrap` signal.
        pub async fn bootstrap(&self, input: BootstrapInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "full.v1.FullService.Bootstrap", &input).await
        }

        /// Run the `full.v1.FullService.Status` query.
        pub async fn status(&self) -> Result<StatusOutput> {
            temporal_runtime::query_proto_empty::<StatusOutput>(&self.inner, "full.v1.FullService.Status").await
        }

        /// Run the `full.v1.FullService.Reconfigure` update.
        pub async fn reconfigure(&self, input: ReconfigureInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<ReconfigureOutput> {
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&self.inner, "full.v1.FullService.Reconfigure", &input, wait_policy).await
        }

    }

    /// Start `full.v1.FullService.Run` and atomically deliver the `full.v1.FullService.Bootstrap` signal.
    pub async fn bootstrap_with_start(
        client: &temporal_runtime::TemporalClient,
        signal_input: BootstrapInput,
        workflow_input: RunInput,
        opts: RunStartOptions,
    ) -> Result<RunHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            run_id(&workflow_input)
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
        let id_reuse_policy = opts.id_reuse_policy.or(Some(temporal_runtime::WorkflowIdReusePolicy::AllowDuplicateFailedOnly));
        let id_conflict_policy = opts.id_conflict_policy;
        let execution_timeout = opts.execution_timeout.or(Some(Duration::from_secs(7200)));
        let run_timeout = opts.run_timeout.or(Some(Duration::from_secs(3600)));
        let task_timeout = opts.task_timeout.or(Some(Duration::from_secs(60)));
        let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
        let retry_policy = opts.retry_policy;
        let inner = temporal_runtime::signal_with_start_workflow_proto(
            client,
            RUN_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "full.v1.FullService.Bootstrap",
            &signal_input,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok(RunHandle { inner })
    }

    /// Start `full.v1.FullService.Run` and atomically deliver the `full.v1.FullService.Reconfigure` update.
    pub async fn reconfigure_with_start(
        client: &temporal_runtime::TemporalClient,
        update_input: ReconfigureInput,
        workflow_input: RunInput,
        opts: RunStartOptions,
        wait_policy: temporal_runtime::WaitPolicy,
    ) -> Result<(RunHandle, ReconfigureOutput)> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            run_id(&workflow_input)
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "full".to_string());
        let id_reuse_policy = opts.id_reuse_policy.or(Some(temporal_runtime::WorkflowIdReusePolicy::AllowDuplicateFailedOnly));
        let id_conflict_policy = opts.id_conflict_policy;
        let execution_timeout = opts.execution_timeout.or(Some(Duration::from_secs(7200)));
        let run_timeout = opts.run_timeout.or(Some(Duration::from_secs(3600)));
        let task_timeout = opts.task_timeout.or(Some(Duration::from_secs(60)));
        let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
        let retry_policy = opts.retry_policy;
        let (inner, update_result) = temporal_runtime::update_with_start_workflow_proto::<RunInput, ReconfigureInput, ReconfigureOutput>(
            client,
            RUN_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "full.v1.FullService.Reconfigure",
            &update_input,
            wait_policy,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok((RunHandle { inner }, update_result))
    }

}
