// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
/// Generated Temporal client + worker surface for `multi.v1.MultiService`.
///
/// Construct a typed client with [`MultiServiceClient::connect`] (or
/// [`MultiServiceClient::new`] from an existing `TemporalClient`).
/// Each workflow rpc gets a typed start method, an attach helper, and a
/// `<Workflow>Handle` wrapper exposing signal / query / update / cancel
/// / terminate / result paths typed against the proto.
///
/// Identity consts (`PACKAGE`, `SERVICE_NAME`, `FULLY_QUALIFIED_SERVICE_NAME`,
/// `SOURCE_FILE`, `GENERATED_BY_PLUGIN_VERSION`) on the client and per-rpc
/// `<RPC>_*` name / type consts at module scope let tooling enumerate the wire
/// surface without descriptor-pool
/// round-trips.
pub mod multi_v1_multi_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::multi::v1::*;

    impl temporal_runtime::TemporalProtoMessage for AlphaInput {
        const MESSAGE_TYPE: &'static str = "multi.v1.AlphaInput";
    }
    impl temporal_runtime::TemporalProtoMessage for AlphaOutput {
        const MESSAGE_TYPE: &'static str = "multi.v1.AlphaOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for BetaInput {
        const MESSAGE_TYPE: &'static str = "multi.v1.BetaInput";
    }
    impl temporal_runtime::TemporalProtoMessage for BetaOutput {
        const MESSAGE_TYPE: &'static str = "multi.v1.BetaOutput";
    }

    pub const PACKAGE: &str = "multi.v1";
    pub const SERVICE_NAME: &str = "MultiService";
    pub const FULLY_QUALIFIED_SERVICE_NAME: &str = "multi.v1.MultiService";
    pub const SOURCE_FILE: &str = "input.proto";
    pub const ALPHA_WORKFLOW_NAME: &str = "multi.v1.MultiService.Alpha";
    pub const ALPHA_INPUT_TYPE: &str = "multi.v1.AlphaInput";
    pub const ALPHA_OUTPUT_TYPE: &str = "multi.v1.AlphaOutput";
    pub const ALPHA_TASK_QUEUE: &str = "multi";
    pub const ALPHA_WORKFLOW_ID_TEMPLATE: &str = "alpha-{{ .Label }}";
    pub const BETA_WORKFLOW_NAME: &str = "multi.v1.MultiService.Beta";
    pub const BETA_INPUT_TYPE: &str = "multi.v1.BetaInput";
    pub const BETA_OUTPUT_TYPE: &str = "multi.v1.BetaOutput";
    pub const BETA_TASK_QUEUE: &str = "multi-beta";

    pub const PING_SIGNAL_INPUT_TYPE: &str = "google.protobuf.Empty";

    fn alpha_id(input: &AlphaInput) -> String {
        let id = format!("alpha-{}", input.label);
        assert!(!id.is_empty(), "workflow id template `alpha-{{}}` resolved to an empty string at runtime — check that every referenced input field has a non-empty value");
        if let Some(bad) = id.chars().find(|c| c.is_control()) {
            panic!("workflow id template `alpha-{{}}` resolved to a value containing control character {:?} at runtime — check the referenced input fields for embedded newlines / tabs", bad);
        }
        id
    }

    #[derive(Clone)]
    pub struct MultiServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for MultiServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("MultiServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for MultiServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl MultiServiceClient {
        pub const PACKAGE: &'static str = "multi.v1";
        pub const SERVICE_NAME: &'static str = "MultiService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "multi.v1.MultiService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const DEFAULT_TASK_QUEUE: &'static str = "multi";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["multi.v1.MultiService.Alpha", "multi.v1.MultiService.Beta"];
        pub const SIGNAL_NAMES: &'static [&'static str] = &["multi.v1.MultiService.Ping"];
        pub const ALL_HANDLER_NAMES: &'static [&'static str] = &["multi.v1.MultiService.Alpha", "multi.v1.MultiService.Beta", "multi.v1.MultiService.Ping"];
        pub const TASK_QUEUES: &'static [&'static str] = &["multi", "multi-beta"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn random_workflow_id() -> String {
            temporal_runtime::random_workflow_id()
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

        pub fn clone_inner(&self) -> temporal_runtime::TemporalClient {
            self.client.clone()
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for MultiServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::TemporalClient> for MultiServiceClient {
        fn as_ref(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }
    }

    impl MultiServiceClient {
        /// Start a new `multi.v1.MultiService.Alpha` workflow.
        pub async fn alpha(
            &self,
            input: AlphaInput,
            opts: AlphaStartOptions,
        ) -> Result<AlphaHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                alpha_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "multi".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                ALPHA_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(AlphaHandle { inner })
        }

        /// Attach to a running `multi.v1.MultiService.Alpha` workflow by id.
        pub fn alpha_handle(&self, workflow_id: impl Into<String>) -> AlphaHandle {
            AlphaHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Start a new `multi.v1.MultiService.Beta` workflow.
        pub async fn beta(
            &self,
            input: BetaInput,
            opts: BetaStartOptions,
        ) -> Result<BetaHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "multi-beta".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout.or(Some(Duration::from_secs(900)));
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                BETA_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(BetaHandle { inner })
        }

        /// Attach to a running `multi.v1.MultiService.Beta` workflow by id.
        pub fn beta_handle(&self, workflow_id: impl Into<String>) -> BetaHandle {
            BetaHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct AlphaStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl AlphaStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
        pub fn is_empty(&self) -> bool {
            self.workflow_id.is_none()
                && self.task_queue.is_none()
                && self.id_reuse_policy.is_none()
                && self.id_conflict_policy.is_none()
                && self.execution_timeout.is_none()
                && self.run_timeout.is_none()
                && self.task_timeout.is_none()
                && self.enable_eager_workflow_start.is_none()
                && self.retry_policy.is_none()
        }
        /// Names of fields with `Some` values, in declaration order. Empty iff [`Self::is_empty`].
        pub fn set_field_names(&self) -> ::std::vec::Vec<&'static str> {
            let mut out = ::std::vec::Vec::new();
            if self.workflow_id.is_some() { out.push("workflow_id"); }
            if self.task_queue.is_some() { out.push("task_queue"); }
            if self.id_reuse_policy.is_some() { out.push("id_reuse_policy"); }
            if self.id_conflict_policy.is_some() { out.push("id_conflict_policy"); }
            if self.execution_timeout.is_some() { out.push("execution_timeout"); }
            if self.run_timeout.is_some() { out.push("run_timeout"); }
            if self.task_timeout.is_some() { out.push("task_timeout"); }
            if self.enable_eager_workflow_start.is_some() { out.push("enable_eager_workflow_start"); }
            if self.retry_policy.is_some() { out.push("retry_policy"); }
            out
        }
    }

    #[derive(Clone)]
    pub struct AlphaHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for AlphaHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("AlphaHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for AlphaHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl AlphaHandle {
        pub const WORKFLOW_NAME: &'static str = self::ALPHA_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::ALPHA_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::ALPHA_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::ALPHA_TASK_QUEUE;
        pub const ID_TEMPLATE: &'static str = self::ALPHA_WORKFLOW_ID_TEMPLATE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for AlphaHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::WorkflowHandle> for AlphaHandle {
        fn as_ref(&self) -> &temporal_runtime::WorkflowHandle {
            &self.inner
        }
    }

    impl ::std::cmp::PartialEq for AlphaHandle {
        fn eq(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
                && self.inner.run_id() == other.inner.run_id()
        }
    }
    impl ::std::cmp::Eq for AlphaHandle {}
    impl ::std::hash::Hash for AlphaHandle {
        fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
            self.inner.workflow_id().hash(state);
            self.inner.run_id().hash(state);
        }
    }
    impl ::std::cmp::PartialOrd for AlphaHandle {
        fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
            Some(self.cmp(other))
        }
    }
    impl ::std::cmp::Ord for AlphaHandle {
        fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
            self.inner.workflow_id().cmp(other.inner.workflow_id())
                .then_with(|| self.inner.run_id().cmp(&other.inner.run_id()))
        }
    }

    impl AlphaHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn client(&self) -> &temporal_runtime::TemporalClient {
            self.inner.client()
        }

        pub fn with_run_id(self, run_id: Option<String>) -> Self {
            Self { inner: self.inner.with_run_id(run_id) }
        }

        pub fn without_run_id(self) -> Self {
            self.with_run_id(None)
        }

        pub fn set_run_id(&mut self, run_id: Option<String>) {
            self.inner = self.inner.clone().with_run_id(run_id);
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        /// `true` IFF both handles carry a known run id, the run ids match,
        /// and the workflow ids match. Returns `false` if either side has
        /// no run id (constructed via `<rpc>_handle`) — strict equality requires
        /// proof, and absence of a run id is not proof. Use [`Self::same_workflow_as`]
        /// for the looser "same workflow id" comparison.
        pub fn same_execution_as(&self, other: &Self) -> bool {
            match (self.inner.run_id(), other.inner.run_id()) {
                (Some(a), Some(b)) => a == b && self.inner.workflow_id() == other.inner.workflow_id(),
                _ => false,
            }
        }

        pub fn clone_inner(&self) -> temporal_runtime::WorkflowHandle {
            self.inner.clone()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<AlphaOutput> {
            temporal_runtime::wait_result_proto::<AlphaOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct BetaStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl BetaStartOptions {
        pub fn default_run_timeout() -> Duration {
            Duration::from_secs(900)
        }
        pub fn proto_defaults() -> Self {
            let mut opts = Self::default();
            opts.run_timeout = Some(Self::default_run_timeout());
            opts
        }
        pub fn with_proto_defaults(mut self) -> Self {
            if self.run_timeout.is_none() {
                self.run_timeout = Some(Self::default_run_timeout());
            }
            self
        }
    }

    impl BetaStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
        pub fn is_empty(&self) -> bool {
            self.workflow_id.is_none()
                && self.task_queue.is_none()
                && self.id_reuse_policy.is_none()
                && self.id_conflict_policy.is_none()
                && self.execution_timeout.is_none()
                && self.run_timeout.is_none()
                && self.task_timeout.is_none()
                && self.enable_eager_workflow_start.is_none()
                && self.retry_policy.is_none()
        }
        /// Names of fields with `Some` values, in declaration order. Empty iff [`Self::is_empty`].
        pub fn set_field_names(&self) -> ::std::vec::Vec<&'static str> {
            let mut out = ::std::vec::Vec::new();
            if self.workflow_id.is_some() { out.push("workflow_id"); }
            if self.task_queue.is_some() { out.push("task_queue"); }
            if self.id_reuse_policy.is_some() { out.push("id_reuse_policy"); }
            if self.id_conflict_policy.is_some() { out.push("id_conflict_policy"); }
            if self.execution_timeout.is_some() { out.push("execution_timeout"); }
            if self.run_timeout.is_some() { out.push("run_timeout"); }
            if self.task_timeout.is_some() { out.push("task_timeout"); }
            if self.enable_eager_workflow_start.is_some() { out.push("enable_eager_workflow_start"); }
            if self.retry_policy.is_some() { out.push("retry_policy"); }
            out
        }
    }

    #[derive(Clone)]
    pub struct BetaHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for BetaHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("BetaHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for BetaHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl BetaHandle {
        pub const WORKFLOW_NAME: &'static str = self::BETA_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::BETA_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::BETA_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::BETA_TASK_QUEUE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for BetaHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::WorkflowHandle> for BetaHandle {
        fn as_ref(&self) -> &temporal_runtime::WorkflowHandle {
            &self.inner
        }
    }

    impl ::std::cmp::PartialEq for BetaHandle {
        fn eq(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
                && self.inner.run_id() == other.inner.run_id()
        }
    }
    impl ::std::cmp::Eq for BetaHandle {}
    impl ::std::hash::Hash for BetaHandle {
        fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
            self.inner.workflow_id().hash(state);
            self.inner.run_id().hash(state);
        }
    }
    impl ::std::cmp::PartialOrd for BetaHandle {
        fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
            Some(self.cmp(other))
        }
    }
    impl ::std::cmp::Ord for BetaHandle {
        fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
            self.inner.workflow_id().cmp(other.inner.workflow_id())
                .then_with(|| self.inner.run_id().cmp(&other.inner.run_id()))
        }
    }

    impl BetaHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn client(&self) -> &temporal_runtime::TemporalClient {
            self.inner.client()
        }

        pub fn with_run_id(self, run_id: Option<String>) -> Self {
            Self { inner: self.inner.with_run_id(run_id) }
        }

        pub fn without_run_id(self) -> Self {
            self.with_run_id(None)
        }

        pub fn set_run_id(&mut self, run_id: Option<String>) {
            self.inner = self.inner.clone().with_run_id(run_id);
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        /// `true` IFF both handles carry a known run id, the run ids match,
        /// and the workflow ids match. Returns `false` if either side has
        /// no run id (constructed via `<rpc>_handle`) — strict equality requires
        /// proof, and absence of a run id is not proof. Use [`Self::same_workflow_as`]
        /// for the looser "same workflow id" comparison.
        pub fn same_execution_as(&self, other: &Self) -> bool {
            match (self.inner.run_id(), other.inner.run_id()) {
                (Some(a), Some(b)) => a == b && self.inner.workflow_id() == other.inner.workflow_id(),
                _ => false,
            }
        }

        pub fn clone_inner(&self) -> temporal_runtime::WorkflowHandle {
            self.inner.clone()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<BetaOutput> {
            temporal_runtime::wait_result_proto::<BetaOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}
