// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod multi_v1_multi_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::multi::v1::*;

    impl temporal_runtime::TemporalProtoMessage for AlphaInput {
        const MESSAGE_TYPE: &'static str = "multi.v1.AlphaInput";
    }
    impl temporal_runtime::TemporalProtoMessage for AlphaOutput {
        const MESSAGE_TYPE: &'static str = "multi.v1.AlphaOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for BetaInput {
        const MESSAGE_TYPE: &'static str = "multi.v1.BetaInput";
    }
    impl temporal_runtime::TemporalProtoMessage for BetaOutput {
        const MESSAGE_TYPE: &'static str = "multi.v1.BetaOutput";
    }

    pub const ALPHA_WORKFLOW_NAME: &str = "multi.v1.MultiService.Alpha";
    pub const ALPHA_TASK_QUEUE: &str = "multi";
    pub const BETA_WORKFLOW_NAME: &str = "multi.v1.MultiService.Beta";
    pub const BETA_TASK_QUEUE: &str = "multi-beta";

    fn alpha_id(input: &AlphaInput) -> String {
        format!("alpha-{}", input.label)
    }

    pub struct MultiServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl MultiServiceClient {
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["multi.v1.MultiService.Alpha", "multi.v1.MultiService.Beta"];
        pub const SIGNAL_NAMES: &'static [&'static str] = &["multi.v1.MultiService.Ping"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `multi.v1.MultiService.Alpha` workflow.
        pub async fn alpha(
            &self,
            input: AlphaInput,
            opts: AlphaStartOptions,
        ) -> Result<AlphaHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                alpha_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "multi".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                ALPHA_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(AlphaHandle { inner })
        }

        /// Attach to a running `multi.v1.MultiService.Alpha` workflow by id.
        pub fn alpha_handle(&self, workflow_id: impl Into<String>) -> AlphaHandle {
            AlphaHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Start a new `multi.v1.MultiService.Beta` workflow.
        pub async fn beta(
            &self,
            input: BetaInput,
            opts: BetaStartOptions,
        ) -> Result<BetaHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "multi-beta".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout.or(Some(Duration::from_secs(900)));
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                BETA_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(BetaHandle { inner })
        }

        /// Attach to a running `multi.v1.MultiService.Beta` workflow by id.
        pub fn beta_handle(&self, workflow_id: impl Into<String>) -> BetaHandle {
            BetaHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct AlphaStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    pub struct AlphaHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl AlphaHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<AlphaOutput> {
            temporal_runtime::wait_result_proto::<AlphaOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct BetaStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl BetaStartOptions {
        pub fn default_run_timeout() -> Duration {
            Duration::from_secs(900)
        }
    }

    pub struct BetaHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl BetaHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<BetaOutput> {
            temporal_runtime::wait_result_proto::<BetaOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}
