// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod eoqu_v1_eoqu_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::eoqu::v1::*;

    impl temporal_runtime::TemporalProtoMessage for AckInput {
        const MESSAGE_TYPE: &'static str = "eoqu.v1.AckInput";
    }
    impl temporal_runtime::TemporalProtoMessage for RunInput {
        const MESSAGE_TYPE: &'static str = "eoqu.v1.RunInput";
    }
    impl temporal_runtime::TemporalProtoMessage for RunOutput {
        const MESSAGE_TYPE: &'static str = "eoqu.v1.RunOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for TouchInput {
        const MESSAGE_TYPE: &'static str = "eoqu.v1.TouchInput";
    }

    pub const RUN_WORKFLOW_NAME: &str = "eoqu.v1.EoquService.Run";
    pub const RUN_TASK_QUEUE: &str = "eoqu";

    pub struct EoquServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl EoquServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `eoqu.v1.EoquService.Run` workflow.
        pub async fn run(
            &self,
            input: RunInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "eoqu".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `eoqu.v1.EoquService.Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<RunOutput> {
            temporal_runtime::wait_result_proto::<RunOutput>(&self.inner).await
        }

        /// Run the `eoqu.v1.EoquService.Ack` query.
        pub async fn ack(&self, input: AckInput) -> Result<()> {
            temporal_runtime::query_unit::<AckInput>(&self.inner, "eoqu.v1.EoquService.Ack", &input).await
        }

        /// Run the `eoqu.v1.EoquService.AckEmpty` query.
        pub async fn ack_empty(&self) -> Result<()> {
            temporal_runtime::query_proto_empty_unit(&self.inner, "eoqu.v1.EoquService.AckEmpty").await
        }

        /// Run the `eoqu.v1.EoquService.Touch` update.
        pub async fn touch(&self, input: TouchInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<()> {
            temporal_runtime::update_unit::<TouchInput>(&self.inner, "eoqu.v1.EoquService.Touch", &input, wait_policy).await
        }

        /// Run the `eoqu.v1.EoquService.TouchEmpty` update.
        pub async fn touch_empty(&self, wait_policy: temporal_runtime::WaitPolicy) -> Result<()> {
            temporal_runtime::update_proto_empty_unit(&self.inner, "eoqu.v1.EoquService.TouchEmpty", wait_policy).await
        }

        /// Run the `eoqu.v1.EoquService.TouchEmptyStart` update.
        pub async fn touch_empty_start(&self, input: TouchInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<()> {
            temporal_runtime::update_unit::<TouchInput>(&self.inner, "eoqu.v1.EoquService.TouchEmptyStart", &input, wait_policy).await
        }

    }

    /// Start `eoqu.v1.EoquService.Run` and atomically deliver the `eoqu.v1.EoquService.TouchEmptyStart` update.
    pub async fn touch_empty_start_with_start(
        client: &temporal_runtime::TemporalClient,
        update_input: TouchInput,
        workflow_input: RunInput,
        opts: RunStartOptions,
        wait_policy: temporal_runtime::WaitPolicy,
    ) -> Result<RunHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            temporal_runtime::random_workflow_id()
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "eoqu".to_string());
        let id_reuse_policy = opts.id_reuse_policy;
        let id_conflict_policy = opts.id_conflict_policy;
        let execution_timeout = opts.execution_timeout;
        let run_timeout = opts.run_timeout;
        let task_timeout = opts.task_timeout;
        let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
        let retry_policy = opts.retry_policy;
        let inner = temporal_runtime::update_with_start_workflow_proto_unit::<RunInput, TouchInput>(
            client,
            RUN_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "eoqu.v1.EoquService.TouchEmptyStart",
            &update_input,
            wait_policy,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok(RunHandle { inner })
    }

}
