// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod wf_v1_order_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::wf::v1::*;

    impl temporal_runtime::TemporalProtoMessage for CancelInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.CancelInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ConfirmInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.ConfirmInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ConfirmOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.ConfirmOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for OrderInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.OrderInput";
    }
    impl temporal_runtime::TemporalProtoMessage for OrderOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.OrderOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for StatusOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.StatusOutput";
    }

    pub const RUN_WORKFLOW_NAME: &str = "wf.v1.OrderService.Run";
    pub const RUN_INPUT_TYPE: &str = "wf.v1.OrderInput";
    pub const RUN_OUTPUT_TYPE: &str = "wf.v1.OrderOutput";
    pub const RUN_TASK_QUEUE: &str = "orders";
    pub const RUN_ATTACHED_SIGNAL_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Cancel"];
    pub const RUN_ATTACHED_QUERY_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Status"];
    pub const RUN_ATTACHED_UPDATE_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Confirm"];

    pub const CANCEL_SIGNAL_INPUT_TYPE: &str = "wf.v1.CancelInput";
    pub const STATUS_QUERY_INPUT_TYPE: &str = "google.protobuf.Empty";
    pub const STATUS_QUERY_OUTPUT_TYPE: &str = "wf.v1.StatusOutput";
    pub const CONFIRM_UPDATE_INPUT_TYPE: &str = "wf.v1.ConfirmInput";
    pub const CONFIRM_UPDATE_OUTPUT_TYPE: &str = "wf.v1.ConfirmOutput";

    fn run_id(input: &OrderInput) -> String {
        format!("order-{}", input.id)
    }

    pub struct OrderServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl OrderServiceClient {
        pub const PACKAGE: &'static str = "wf.v1";
        pub const SERVICE_NAME: &'static str = "OrderService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "wf.v1.OrderService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Run"];
        pub const SIGNAL_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Cancel"];
        pub const QUERY_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Status"];
        pub const UPDATE_NAMES: &'static [&'static str] = &["wf.v1.OrderService.Confirm"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `wf.v1.OrderService.Run` workflow.
        pub async fn run(
            &self,
            input: OrderInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "orders".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `wf.v1.OrderService.Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Send the `wf.v1.OrderService.Cancel` signal to a workflow by id.
        pub async fn cancel(&self, workflow_id: impl Into<String>, input: CancelInput) -> Result<()> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::signal_proto(&inner, "wf.v1.OrderService.Cancel", &input).await
        }

        /// Run the `wf.v1.OrderService.Status` query against a workflow by id.
        pub async fn status(&self, workflow_id: impl Into<String>) -> Result<StatusOutput> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::query_proto_empty::<StatusOutput>(&inner, "wf.v1.OrderService.Status").await
        }

        /// Run the `wf.v1.OrderService.Confirm` update against a workflow by id.
        pub async fn confirm(&self, workflow_id: impl Into<String>, input: ConfirmInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ConfirmOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::update_proto::<ConfirmInput, ConfirmOutput>(&inner, "wf.v1.OrderService.Confirm", &input, wait_policy).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl RunStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<OrderOutput> {
            temporal_runtime::wait_result_proto::<OrderOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

        /// Send the `wf.v1.OrderService.Cancel` signal.
        pub async fn cancel(&self, input: CancelInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "wf.v1.OrderService.Cancel", &input).await
        }

        /// Run the `wf.v1.OrderService.Status` query.
        pub async fn status(&self) -> Result<StatusOutput> {
            temporal_runtime::query_proto_empty::<StatusOutput>(&self.inner, "wf.v1.OrderService.Status").await
        }

        /// Run the `wf.v1.OrderService.Confirm` update.
        pub async fn confirm(&self, input: ConfirmInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ConfirmOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            temporal_runtime::update_proto::<ConfirmInput, ConfirmOutput>(&self.inner, "wf.v1.OrderService.Confirm", &input, wait_policy).await
        }

    }


    // ── Workflow handler names ──────────────────────────────
    // Phase 3.0 (workflows=true): per-rpc registration name consts.
    // Reference these from your hand-rolled #[workflow] setup so
    // signal/query/update names stay in sync with the proto.

    pub const CANCEL_SIGNAL_NAME: &str = "wf.v1.OrderService.Cancel";
    pub const STATUS_QUERY_NAME: &str = "wf.v1.OrderService.Status";
    pub const CONFIRM_UPDATE_NAME: &str = "wf.v1.OrderService.Confirm";

    // ── Workflow handler I/O aliases ────────────────────────
    // R2 (workflows=true): per-handler type aliases so workflow body
    // signatures can spell `CancelSignalInput` instead of repeating
    // the prost message name.

    pub type CancelSignalInput = CancelInput;
    pub type StatusQueryOutput = StatusOutput;
    pub type ConfirmUpdateInput = ConfirmInput;
    pub type ConfirmUpdateOutput = ConfirmOutput;

    // -- Workflow definitions --------------------------------
    // workflows=true: typed proto contracts + registration helpers.
    // The consumer owns the temporalio-sdk #[workflow] body and
    // implements the matching <Workflow>Definition trait on it.

    pub trait RunDefinition: 'static {
        type Input;
        type Output;
        const WORKFLOW_NAME: &'static str = self::RUN_WORKFLOW_NAME;
        const TASK_QUEUE: &'static str = self::RUN_TASK_QUEUE;
        const CANCEL_SIGNAL_NAME: &'static str = self::CANCEL_SIGNAL_NAME;
        const STATUS_QUERY_NAME: &'static str = self::STATUS_QUERY_NAME;
        const CONFIRM_UPDATE_NAME: &'static str = self::CONFIRM_UPDATE_NAME;
    }

    pub fn register_run_workflow<W>(worker: &mut temporal_runtime::worker::Worker) -> &mut temporal_runtime::worker::Worker
    where
        W: temporal_runtime::worker::WorkflowImplementer + RunDefinition<Input = OrderInput, Output = OrderOutput>,
    {
        worker.register_workflow::<W>()
    }

    pub struct RunWorkflow;
    impl temporal_runtime::worker::WorkflowDefinition for RunWorkflow {
        type Input = temporal_runtime::TypedProtoMessage<OrderInput>;
        type Output = temporal_runtime::TypedProtoMessage<OrderOutput>;
        fn name(&self) -> &str { self::RUN_WORKFLOW_NAME }
    }
    pub async fn start_run_child<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: OrderInput,
        opts: temporal_runtime::worker::ChildWorkflowOptions,
    ) -> ::std::result::Result<temporal_runtime::worker::StartedChildWorkflow<RunWorkflow>, temporal_runtime::worker::ChildWorkflowStartError> {
        ctx.child_workflow(RunWorkflow, input, opts).await
    }

    pub fn continue_run_as_new<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: OrderInput,
        opts: temporal_runtime::worker::ContinueAsNewOptions,
    ) -> ::std::result::Result<::std::convert::Infallible, temporal_runtime::worker::WorkflowTermination>
    where
        W: temporal_runtime::worker::WorkflowImplementation<Run = RunWorkflow>,
    {
        let wrapped = temporal_runtime::TypedProtoMessage::from(input);
        ctx.continue_as_new(&wrapped, opts)
    }

    pub struct CancelSignal;
    impl temporal_runtime::worker::SignalDefinition for CancelSignal {
        type Workflow = RunWorkflow;
        type Input = temporal_runtime::TypedProtoMessage<CancelInput>;
        fn name(&self) -> &str { self::CANCEL_SIGNAL_NAME }
    }
    pub async fn signal_cancel_external<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        workflow_id: impl Into<String>,
        run_id: Option<String>,
        input: CancelInput,
    ) -> temporal_runtime::worker::SignalExternalWfResult {
        let handle = ctx.external_workflow(workflow_id, run_id);
        handle.signal(CancelSignal, temporal_runtime::TypedProtoMessage::from(input)).await
    }

}
