// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod wf_v1_order_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::wf::v1::*;

    impl temporal_runtime::TemporalProtoMessage for CancelInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.CancelInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ConfirmInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.ConfirmInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ConfirmOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.ConfirmOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for OrderInput {
        const MESSAGE_TYPE: &'static str = "wf.v1.OrderInput";
    }
    impl temporal_runtime::TemporalProtoMessage for OrderOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.OrderOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for StatusOutput {
        const MESSAGE_TYPE: &'static str = "wf.v1.StatusOutput";
    }

    pub const RUN_WORKFLOW_NAME: &str = "wf.v1.OrderService.Run";
    pub const RUN_TASK_QUEUE: &str = "orders";

    fn run_id(input: &OrderInput) -> String {
        format!("order-{}", input.id)
    }

    pub struct OrderServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl OrderServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `wf.v1.OrderService.Run` workflow.
        pub async fn run(
            &self,
            input: OrderInput,
            opts: RunStartOptions,
        ) -> Result<RunHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "orders".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
            ).await?;
            Ok(RunHandle { inner })
        }

        /// Attach to a running `wf.v1.OrderService.Run` workflow by id.
        pub fn run_handle(&self, workflow_id: impl Into<String>) -> RunHandle {
            RunHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
    }

    pub struct RunHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<OrderOutput> {
            temporal_runtime::wait_result_proto::<OrderOutput>(&self.inner).await
        }

        /// Send the `wf.v1.OrderService.Cancel` signal.
        pub async fn cancel(&self, input: CancelInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "wf.v1.OrderService.Cancel", &input).await
        }

        /// Run the `wf.v1.OrderService.Status` query.
        pub async fn status(&self) -> Result<StatusOutput> {
            temporal_runtime::query_proto_empty::<StatusOutput>(&self.inner, "wf.v1.OrderService.Status").await
        }

        /// Run the `wf.v1.OrderService.Confirm` update.
        pub async fn confirm(&self, input: ConfirmInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<ConfirmOutput> {
            temporal_runtime::update_proto::<ConfirmInput, ConfirmOutput>(&self.inner, "wf.v1.OrderService.Confirm", &input, wait_policy).await
        }

    }


    // ── Workflow handler names ──────────────────────────────
    // Phase 3.0 (workflows=true): per-rpc registration name consts.
    // Reference these from your hand-rolled #[workflow] setup so
    // signal/query/update names stay in sync with the proto.

    pub const CANCEL_SIGNAL_NAME: &str = "wf.v1.OrderService.Cancel";
    pub const STATUS_QUERY_NAME: &str = "wf.v1.OrderService.Status";
    pub const CONFIRM_UPDATE_NAME: &str = "wf.v1.OrderService.Confirm";

    // -- Workflow definitions --------------------------------
    // workflows=true: typed proto contracts + registration helpers.
    // The consumer owns the temporalio-sdk #[workflow] body and
    // implements the matching <Workflow>Definition trait on it.

    pub trait RunDefinition: 'static {
        type Input;
        type Output;
        const WORKFLOW_NAME: &'static str = self::RUN_WORKFLOW_NAME;
        const TASK_QUEUE: &'static str = self::RUN_TASK_QUEUE;
        const CANCEL_SIGNAL_NAME: &'static str = self::CANCEL_SIGNAL_NAME;
        const STATUS_QUERY_NAME: &'static str = self::STATUS_QUERY_NAME;
        const CONFIRM_UPDATE_NAME: &'static str = self::CONFIRM_UPDATE_NAME;
    }

    pub fn register_run_workflow<W>(worker: &mut temporal_runtime::worker::Worker) -> &mut temporal_runtime::worker::Worker
    where
        W: temporal_runtime::worker::WorkflowImplementer + RunDefinition<Input = OrderInput, Output = OrderOutput>,
    {
        worker.register_workflow::<W>()
    }

}
