// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod acts_v1_chunk_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::acts::v1::*;

    impl temporal_runtime::TemporalProtoMessage for BatchInput {
        const MESSAGE_TYPE: &'static str = "acts.v1.BatchInput";
    }
    impl temporal_runtime::TemporalProtoMessage for BatchOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.BatchOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for ChunkInput {
        const MESSAGE_TYPE: &'static str = "acts.v1.ChunkInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ChunkOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.ChunkOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for HeartbeatOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.HeartbeatOutput";
    }

    pub const RUN_BATCH_WORKFLOW_NAME: &str = "acts.v1.ChunkService.RunBatch";
    pub const RUN_BATCH_INPUT_TYPE: &str = "acts.v1.BatchInput";
    pub const RUN_BATCH_OUTPUT_TYPE: &str = "acts.v1.BatchOutput";
    pub const RUN_BATCH_TASK_QUEUE: &str = "chunks";
    pub const RUN_BATCH_WORKFLOW_ID_TEMPLATE: &str = "batch-{{ .Name }}";

    pub const PROCESS_ACTIVITY_INPUT_TYPE: &str = "acts.v1.ChunkInput";
    pub const PROCESS_ACTIVITY_OUTPUT_TYPE: &str = "acts.v1.ChunkOutput";
    pub const HEARTBEAT_ACTIVITY_INPUT_TYPE: &str = "google.protobuf.Empty";
    pub const HEARTBEAT_ACTIVITY_OUTPUT_TYPE: &str = "acts.v1.HeartbeatOutput";

    fn run_batch_id(input: &BatchInput) -> String {
        let id = format!("batch-{}", input.name);
        assert!(!id.is_empty(), "workflow id template `batch-{{}}` resolved to an empty string at runtime — check that every referenced input field has a non-empty value");
        if let Some(bad) = id.chars().find(|c| c.is_control()) {
            panic!("workflow id template `batch-{{}}` resolved to a value containing control character {:?} at runtime — check the referenced input fields for embedded newlines / tabs", bad);
        }
        id
    }

    #[derive(Clone)]
    pub struct ChunkServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for ChunkServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("ChunkServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for ChunkServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl ChunkServiceClient {
        pub const PACKAGE: &'static str = "acts.v1";
        pub const SERVICE_NAME: &'static str = "ChunkService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "acts.v1.ChunkService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["acts.v1.ChunkService.RunBatch"];
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["acts.v1.ChunkService.Process", "acts.v1.ChunkService.Heartbeat"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for ChunkServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ChunkServiceClient {
        /// Start a new `acts.v1.ChunkService.RunBatch` workflow.
        pub async fn run_batch(
            &self,
            input: BatchInput,
            opts: RunBatchStartOptions,
        ) -> Result<RunBatchHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_batch_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "chunks".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_BATCH_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(RunBatchHandle { inner })
        }

        /// Attach to a running `acts.v1.ChunkService.RunBatch` workflow by id.
        pub fn run_batch_handle(&self, workflow_id: impl Into<String>) -> RunBatchHandle {
            RunBatchHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunBatchStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl RunBatchStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
    }

    #[derive(Clone)]
    pub struct RunBatchHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for RunBatchHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("RunBatchHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for RunBatchHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl RunBatchHandle {
        pub const WORKFLOW_NAME: &'static str = self::RUN_BATCH_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::RUN_BATCH_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::RUN_BATCH_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::RUN_BATCH_TASK_QUEUE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for RunBatchHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl RunBatchHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<BatchOutput> {
            temporal_runtime::wait_result_proto::<BatchOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }


    // ── Activities ────────────────────────────────────────────
    // Phase 2 (activities=true): typed trait + name consts. Wire to
    // your worker via temporalio-sdk's #[activities] macro;
    // see temporal-proto-runtime-bridge README for the adapter pattern.

    pub const PROCESS_ACTIVITY_NAME: &str = "acts.v1.ChunkService.Process";
    pub const HEARTBEAT_ACTIVITY_NAME: &str = "acts.v1.ChunkService.Heartbeat";

    #[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
    pub struct ProcessActivity;
    impl temporal_runtime::worker::ActivityDefinition for ProcessActivity {
        type Input = temporal_runtime::TypedProtoMessage<ChunkInput>;
        type Output = temporal_runtime::TypedProtoMessage<ChunkOutput>;
        fn name() -> &'static str { PROCESS_ACTIVITY_NAME }
    }
    impl ProcessActivity {
        pub const NAME: &'static str = self::PROCESS_ACTIVITY_NAME;
        pub const INPUT_TYPE: &'static str = self::PROCESS_ACTIVITY_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::PROCESS_ACTIVITY_OUTPUT_TYPE;
    }
    pub async fn execute_process<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: ChunkInput,
        opts: temporal_runtime::worker::ActivityOptions,
    ) -> ::std::result::Result<ChunkOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_activity(ProcessActivity, input, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }
    pub async fn execute_process_local<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: ChunkInput,
        opts: temporal_runtime::worker::LocalActivityOptions,
    ) -> ::std::result::Result<ChunkOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_local_activity(ProcessActivity, input, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }
    #[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
    pub struct HeartbeatActivity;
    impl temporal_runtime::worker::ActivityDefinition for HeartbeatActivity {
        type Input = temporal_runtime::TypedProtoMessage<temporal_runtime::ProtoEmpty>;
        type Output = temporal_runtime::TypedProtoMessage<HeartbeatOutput>;
        fn name() -> &'static str { HEARTBEAT_ACTIVITY_NAME }
    }
    impl HeartbeatActivity {
        pub const NAME: &'static str = self::HEARTBEAT_ACTIVITY_NAME;
        pub const INPUT_TYPE: &'static str = self::HEARTBEAT_ACTIVITY_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::HEARTBEAT_ACTIVITY_OUTPUT_TYPE;
    }
    pub async fn execute_heartbeat<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        opts: temporal_runtime::worker::ActivityOptions,
    ) -> ::std::result::Result<HeartbeatOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_activity(HeartbeatActivity, temporal_runtime::ProtoEmpty {}, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }
    pub async fn execute_heartbeat_local<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        opts: temporal_runtime::worker::LocalActivityOptions,
    ) -> ::std::result::Result<HeartbeatOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_local_activity(HeartbeatActivity, temporal_runtime::ProtoEmpty {}, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }

    pub trait ChunkServiceActivities: Send + Sync + 'static {
        fn process(&self, ctx: temporal_runtime::ActivityContext, input: ChunkInput) -> impl ::std::future::Future<Output = Result<ChunkOutput>> + Send;
        fn heartbeat(&self, ctx: temporal_runtime::ActivityContext, input: ()) -> impl ::std::future::Future<Output = Result<HeartbeatOutput>> + Send;
    }

    pub fn register_chunk_service_activities<I>(worker: &mut temporal_runtime::worker::Worker, impl_: I) -> &mut temporal_runtime::worker::Worker
    where
        I: ChunkServiceActivities + temporal_runtime::worker::ActivityImplementer,
    {
        worker.register_activities(impl_)
    }
}
