// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod acts_v1_chunk_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::acts::v1::*;

    impl temporal_runtime::TemporalProtoMessage for BatchInput {
        const MESSAGE_TYPE: &'static str = "acts.v1.BatchInput";
    }
    impl temporal_runtime::TemporalProtoMessage for BatchOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.BatchOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for ChunkInput {
        const MESSAGE_TYPE: &'static str = "acts.v1.ChunkInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ChunkOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.ChunkOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for HeartbeatOutput {
        const MESSAGE_TYPE: &'static str = "acts.v1.HeartbeatOutput";
    }

    pub const RUN_BATCH_WORKFLOW_NAME: &str = "acts.v1.ChunkService.RunBatch";
    pub const RUN_BATCH_TASK_QUEUE: &str = "chunks";

    fn run_batch_id(input: &BatchInput) -> String {
        format!("batch-{}", input.name)
    }

    pub struct ChunkServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ChunkServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `acts.v1.ChunkService.RunBatch` workflow.
        pub async fn run_batch(
            &self,
            input: BatchInput,
            opts: RunBatchStartOptions,
        ) -> Result<RunBatchHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_batch_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "chunks".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_BATCH_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
            ).await?;
            Ok(RunBatchHandle { inner })
        }

        /// Attach to a running `acts.v1.ChunkService.RunBatch` workflow by id.
        pub fn run_batch_handle(&self, workflow_id: impl Into<String>) -> RunBatchHandle {
            RunBatchHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunBatchStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    pub struct RunBatchHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunBatchHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<BatchOutput> {
            temporal_runtime::wait_result_proto::<BatchOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }


    // ── Activities ────────────────────────────────────────────
    // Phase 2 (activities=true): typed trait + name consts. Wire to
    // your worker via temporalio-sdk's #[activities] macro;
    // see temporal-proto-runtime-bridge README for the adapter pattern.

    pub const PROCESS_ACTIVITY_NAME: &str = "acts.v1.ChunkService.Process";
    pub const HEARTBEAT_ACTIVITY_NAME: &str = "acts.v1.ChunkService.Heartbeat";

    pub trait ChunkServiceActivities: Send + Sync + 'static {
        fn process(&self, ctx: temporal_runtime::ActivityContext, input: ChunkInput) -> impl ::std::future::Future<Output = Result<ChunkOutput>> + Send;
        fn heartbeat(&self, ctx: temporal_runtime::ActivityContext, input: ()) -> impl ::std::future::Future<Output = Result<HeartbeatOutput>> + Send;
    }

    pub fn register_chunk_service_activities<I>(worker: &mut temporal_runtime::worker::Worker, impl_: I) -> &mut temporal_runtime::worker::Worker
    where
        I: ChunkServiceActivities + temporal_runtime::worker::ActivityImplementer,
    {
        worker.register_activities(impl_)
    }
}
