// Code generated by protoc-gen-rust-temporal v0.1.1. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
/// Generated Temporal client + worker surface for `act.v1.WorkerOnlyService`.
///
/// Construct a typed client with [`WorkerOnlyServiceClient::connect`] (or
/// [`WorkerOnlyServiceClient::new`] from an existing `TemporalClient`).
/// Each workflow rpc gets a typed start method, an attach helper, and a
/// `<Workflow>Handle` wrapper exposing signal / query / update / cancel
/// / terminate / result paths typed against the proto.
///
/// Identity consts (`PACKAGE`, `SERVICE_NAME`, `FULLY_QUALIFIED_SERVICE_NAME`,
/// `SOURCE_FILE`, `GENERATED_BY_PLUGIN_VERSION`) on the client and per-rpc
/// `<RPC>_*` name / type consts at module scope let tooling enumerate the wire
/// surface without descriptor-pool
/// round-trips.
pub mod act_v1_worker_only_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::act::v1::*;

    pub const PACKAGE: &str = "act.v1";
    pub const SERVICE_NAME: &str = "WorkerOnlyService";
    pub const FULLY_QUALIFIED_SERVICE_NAME: &str = "act.v1.WorkerOnlyService";
    pub const SOURCE_FILE: &str = "input.proto";
    pub const CLUDDEN_SCHEMA_DIGEST: &str = "buf.build/cludden/protoc-gen-go-temporal:6d988a28838c46ebb99eaa042cf2a607";
    pub const WIRE_FORMAT_VERSION: &str = "v1";
    pub const PLUGIN_VERSION: &str = "protoc-gen-rust-temporal 0.1.1";
    pub const PROCESS_CHUNK_ACTIVITY_INPUT_TYPE: &str = "act.v1.ChunkInput";
    pub const PROCESS_CHUNK_ACTIVITY_OUTPUT_TYPE: &str = "act.v1.ChunkOutput";
    pub const CLEANUP_ACTIVITY_INPUT_TYPE: &str = "act.v1.CleanupInput";
    pub const CLEANUP_ACTIVITY_OUTPUT_TYPE: &str = "act.v1.CleanupOutput";

    #[derive(Clone)]
    pub struct WorkerOnlyServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for WorkerOnlyServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("WorkerOnlyServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for WorkerOnlyServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl WorkerOnlyServiceClient {
        pub const PACKAGE: &'static str = "act.v1";
        pub const SERVICE_NAME: &'static str = "WorkerOnlyService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "act.v1.WorkerOnlyService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["act.v1.WorkerOnlyService.ProcessChunk", "act.v1.WorkerOnlyService.Cleanup"];
        pub const ALL_HANDLER_NAMES: &'static [&'static str] = &["act.v1.WorkerOnlyService.ProcessChunk", "act.v1.WorkerOnlyService.Cleanup"];
        pub const HANDLER_COUNT: usize = Self::ALL_HANDLER_NAMES.len();
        pub const ACTIVITY_COUNT: usize = Self::ACTIVITY_NAMES.len();

        /// Look up which handler kind a registered name belongs to.
        /// Returns `"workflow"` / `"signal"` / `"query"` / `"update"` / `"activity"`,
        /// or `None` if the name doesn't match any handler this service registers.
        pub fn lookup_handler_kind(name: &str) -> Option<&'static str> {
            if Self::ACTIVITY_NAMES.contains(&name) { return Some("activity"); }
            None
        }
        /// `true` if `name` is registered on this service (any kind).
        /// Sugar over [`Self::lookup_handler_kind`]`(name).is_some()`.
        pub fn has_handler(name: &str) -> bool {
            Self::lookup_handler_kind(name).is_some()
        }

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn random_workflow_id() -> String {
            temporal_runtime::random_workflow_id()
        }
        /// Random UUID-based workflow id with `prefix` prepended.
        /// Sugar for `format!("{prefix}{}", Self::random_workflow_id())`.
        pub fn random_workflow_id_with_prefix(prefix: impl ::std::fmt::Display) -> String {
            ::std::format!("{}{}", prefix, Self::random_workflow_id())
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

        pub fn clone_inner(&self) -> temporal_runtime::TemporalClient {
            self.client.clone()
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for WorkerOnlyServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::TemporalClient> for WorkerOnlyServiceClient {
        fn as_ref(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }
    }

    impl WorkerOnlyServiceClient {
    }

}
