// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod act_v1_worker_only_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::act::v1::*;

    pub const PROCESS_CHUNK_ACTIVITY_INPUT_TYPE: &str = "act.v1.ChunkInput";
    pub const PROCESS_CHUNK_ACTIVITY_OUTPUT_TYPE: &str = "act.v1.ChunkOutput";
    pub const CLEANUP_ACTIVITY_INPUT_TYPE: &str = "act.v1.CleanupInput";
    pub const CLEANUP_ACTIVITY_OUTPUT_TYPE: &str = "act.v1.CleanupOutput";

    pub struct WorkerOnlyServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl WorkerOnlyServiceClient {
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["act.v1.WorkerOnlyService.ProcessChunk", "act.v1.WorkerOnlyService.Cleanup"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

    }

}
