// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod jobs_v1_job_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::jobs::v1::*;

    impl temporal_runtime::TemporalProtoMessage for CancelJobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.CancelJobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobStatusOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobStatusOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureOutput";
    }

    pub const RUN_JOB_WORKFLOW_NAME: &str = "jobs.v1.JobService.RunJob";
    pub const RUN_JOB_TASK_QUEUE: &str = "jobs";

    fn run_job_id(input: &JobInput) -> String {
        format!("{}", input.name)
    }

    pub struct JobServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl JobServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `jobs.v1.JobService.RunJob` workflow.
        pub async fn run_job(
            &self,
            input: JobInput,
            opts: RunJobStartOptions,
        ) -> Result<RunJobHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_job_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_JOB_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
            ).await?;
            Ok(RunJobHandle { inner })
        }

        /// Attach to a running `jobs.v1.JobService.RunJob` workflow by id.
        pub fn run_job_handle(&self, workflow_id: impl Into<String>) -> RunJobHandle {
            RunJobHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunJobStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
    }

    pub struct RunJobHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunJobHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<JobOutput> {
            temporal_runtime::wait_result_proto::<JobOutput>(&self.inner).await
        }

        /// Send the `jobs.v1.JobService.CancelJob` signal.
        pub async fn cancel_job(&self, input: CancelJobInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "jobs.v1.JobService.CancelJob", &input).await
        }

        /// Run the `jobs.v1.JobService.GetStatus` query.
        pub async fn get_status(&self) -> Result<JobStatusOutput> {
            temporal_runtime::query_proto_empty::<JobStatusOutput>(&self.inner, "jobs.v1.JobService.GetStatus").await
        }

        /// Run the `jobs.v1.JobService.Reconfigure` update.
        pub async fn reconfigure(&self, input: ReconfigureInput, wait_policy: temporal_runtime::WaitPolicy) -> Result<ReconfigureOutput> {
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&self.inner, "jobs.v1.JobService.Reconfigure", &input, wait_policy).await
        }

    }

    /// Start `jobs.v1.JobService.RunJob` and atomically deliver the `jobs.v1.JobService.CancelJob` signal.
    pub async fn cancel_job_with_start(
        client: &temporal_runtime::TemporalClient,
        signal_input: CancelJobInput,
        workflow_input: JobInput,
        opts: RunJobStartOptions,
    ) -> Result<RunJobHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            run_job_id(&workflow_input)
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
        let id_reuse_policy = opts.id_reuse_policy;
        let execution_timeout = opts.execution_timeout;
        let run_timeout = opts.run_timeout;
        let task_timeout = opts.task_timeout;
        let inner = temporal_runtime::signal_with_start_workflow_proto(
            client,
            RUN_JOB_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "jobs.v1.JobService.CancelJob",
            &signal_input,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok(RunJobHandle { inner })
    }

}
