// Code generated by protoc-gen-rust-temporal v0.1.1. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
/// Generated Temporal client + worker surface for `jobs.v1.JobService`.
///
/// Construct a typed client with [`JobServiceClient::connect`] (or
/// [`JobServiceClient::new`] from an existing `TemporalClient`).
/// Each workflow rpc gets a typed start method, an attach helper, and a
/// `<Workflow>Handle` wrapper exposing signal / query / update / cancel
/// / terminate / result paths typed against the proto.
///
/// Identity consts (`PACKAGE`, `SERVICE_NAME`, `FULLY_QUALIFIED_SERVICE_NAME`,
/// `SOURCE_FILE`, `GENERATED_BY_PLUGIN_VERSION`) on the client and per-rpc
/// `<RPC>_*` name / type consts at module scope let tooling enumerate the wire
/// surface without descriptor-pool
/// round-trips.
pub mod jobs_v1_job_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::jobs::v1::*;

    impl temporal_runtime::TemporalProtoMessage for CancelJobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.CancelJobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobStatusOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobStatusOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureOutput";
    }

    pub const PACKAGE: &str = "jobs.v1";
    pub const SERVICE_NAME: &str = "JobService";
    pub const FULLY_QUALIFIED_SERVICE_NAME: &str = "jobs.v1.JobService";
    pub const SOURCE_FILE: &str = "input.proto";
    pub const CLUDDEN_SCHEMA_DIGEST: &str = "buf.build/cludden/protoc-gen-go-temporal:6d988a28838c46ebb99eaa042cf2a607";
    pub const WIRE_FORMAT_VERSION: &str = "v1";
    pub const PLUGIN_VERSION: &str = "protoc-gen-rust-temporal 0.1.1";
    pub const RUN_JOB_WORKFLOW_NAME: &str = "jobs.v1.JobService.RunJob";
    pub const RUN_JOB_INPUT_TYPE: &str = "jobs.v1.JobInput";
    pub const RUN_JOB_OUTPUT_TYPE: &str = "jobs.v1.JobOutput";
    pub const RUN_JOB_TASK_QUEUE: &str = "jobs";
    pub const RUN_JOB_WORKFLOW_ID_TEMPLATE: &str = "{{ .Name }}";
    pub const RUN_JOB_ATTACHED_SIGNAL_NAMES: &'static [&'static str] = &["jobs.v1.JobService.CancelJob"];
    pub const RUN_JOB_ATTACHED_QUERY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.GetStatus"];
    pub const RUN_JOB_ATTACHED_UPDATE_NAMES: &'static [&'static str] = &["jobs.v1.JobService.Reconfigure"];

    pub const CANCEL_JOB_SIGNAL_INPUT_TYPE: &str = "jobs.v1.CancelJobInput";
    pub const GET_STATUS_QUERY_INPUT_TYPE: &str = "google.protobuf.Empty";
    pub const GET_STATUS_QUERY_OUTPUT_TYPE: &str = "jobs.v1.JobStatusOutput";
    pub const RECONFIGURE_UPDATE_INPUT_TYPE: &str = "jobs.v1.ReconfigureInput";
    pub const RECONFIGURE_UPDATE_OUTPUT_TYPE: &str = "jobs.v1.ReconfigureOutput";
    pub const PROCESS_CHUNK_ACTIVITY_INPUT_TYPE: &str = "jobs.v1.ChunkInput";
    pub const PROCESS_CHUNK_ACTIVITY_OUTPUT_TYPE: &str = "jobs.v1.ChunkOutput";

    fn run_job_id(input: &JobInput) -> String {
        let id = format!("{}", input.name);
        assert!(!id.is_empty(), "workflow id template `{{}}` resolved to an empty string at runtime — check that every referenced input field has a non-empty value");
        if let Some(bad) = id.chars().find(|c| c.is_control()) {
            panic!("workflow id template `{{}}` resolved to a value containing control character {:?} at runtime — check the referenced input fields for embedded newlines / tabs", bad);
        }
        id
    }

    #[derive(Clone)]
    pub struct JobServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for JobServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("JobServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for JobServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl JobServiceClient {
        pub const PACKAGE: &'static str = "jobs.v1";
        pub const SERVICE_NAME: &'static str = "JobService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "jobs.v1.JobService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const DEFAULT_TASK_QUEUE: &'static str = "jobs";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["jobs.v1.JobService.RunJob"];
        pub const SIGNAL_NAMES: &'static [&'static str] = &["jobs.v1.JobService.CancelJob"];
        pub const QUERY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.GetStatus"];
        pub const UPDATE_NAMES: &'static [&'static str] = &["jobs.v1.JobService.Reconfigure"];
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.ProcessChunk"];
        pub const ALL_HANDLER_NAMES: &'static [&'static str] = &["jobs.v1.JobService.RunJob", "jobs.v1.JobService.CancelJob", "jobs.v1.JobService.GetStatus", "jobs.v1.JobService.Reconfigure", "jobs.v1.JobService.ProcessChunk"];
        pub const HANDLER_COUNT: usize = Self::ALL_HANDLER_NAMES.len();
        pub const WORKFLOW_COUNT: usize = Self::WORKFLOW_NAMES.len();
        pub const SIGNAL_COUNT: usize = Self::SIGNAL_NAMES.len();
        pub const QUERY_COUNT: usize = Self::QUERY_NAMES.len();
        pub const UPDATE_COUNT: usize = Self::UPDATE_NAMES.len();
        pub const ACTIVITY_COUNT: usize = Self::ACTIVITY_NAMES.len();
        pub const TASK_QUEUES: &'static [&'static str] = &["jobs"];

        /// Look up which handler kind a registered name belongs to.
        /// Returns `"workflow"` / `"signal"` / `"query"` / `"update"` / `"activity"`,
        /// or `None` if the name doesn't match any handler this service registers.
        pub fn lookup_handler_kind(name: &str) -> Option<&'static str> {
            if Self::WORKFLOW_NAMES.contains(&name) { return Some("workflow"); }
            if Self::SIGNAL_NAMES.contains(&name) { return Some("signal"); }
            if Self::QUERY_NAMES.contains(&name) { return Some("query"); }
            if Self::UPDATE_NAMES.contains(&name) { return Some("update"); }
            if Self::ACTIVITY_NAMES.contains(&name) { return Some("activity"); }
            None
        }
        /// `true` if `name` is registered on this service (any kind).
        /// Sugar over [`Self::lookup_handler_kind`]`(name).is_some()`.
        pub fn has_handler(name: &str) -> bool {
            Self::lookup_handler_kind(name).is_some()
        }

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn random_workflow_id() -> String {
            temporal_runtime::random_workflow_id()
        }
        /// Random UUID-based workflow id with `prefix` prepended.
        /// Sugar for `format!("{prefix}{}", Self::random_workflow_id())`.
        pub fn random_workflow_id_with_prefix(prefix: impl ::std::fmt::Display) -> String {
            ::std::format!("{}{}", prefix, Self::random_workflow_id())
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

        pub fn clone_inner(&self) -> temporal_runtime::TemporalClient {
            self.client.clone()
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for JobServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::TemporalClient> for JobServiceClient {
        fn as_ref(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }
    }

    impl JobServiceClient {
        /// Start a new `jobs.v1.JobService.RunJob` workflow.
        pub async fn run_job(
            &self,
            input: JobInput,
            opts: RunJobStartOptions,
        ) -> Result<RunJobHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_job_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_JOB_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(RunJobHandle { inner })
        }

        /// Attach to a running `jobs.v1.JobService.RunJob` workflow by id.
        pub fn run_job_handle(&self, workflow_id: impl Into<String>) -> RunJobHandle {
            RunJobHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Attach to multiple running `jobs.v1.JobService.RunJob` workflows by id.
        /// Sugar for `ids.into_iter().map(|id| client.run_job_handle(id)).collect()`.
        pub fn run_job_handles<I, S>(&self, workflow_ids: I) -> ::std::vec::Vec<RunJobHandle>
        where
            I: IntoIterator<Item = S>,
            S: Into<String>,
        {
            workflow_ids.into_iter().map(|id| self.run_job_handle(id)).collect()
        }

        /// Start a new `jobs.v1.JobService.RunJob` workflow and block on its result.
        /// Sugar for `client.run_job(...).await?.result().await`.
        pub async fn run_job_and_wait(
            &self,
            input: JobInput,
            opts: RunJobStartOptions,
        ) -> Result<JobOutput> {
            let handle = self.run_job(input, opts).await?;
            handle.result().await
        }

        /// Send the `jobs.v1.JobService.CancelJob` signal to a workflow by id.
        pub async fn cancel_job(&self, workflow_id: impl Into<String>, input: CancelJobInput) -> Result<()> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::signal_proto(&inner, "jobs.v1.JobService.CancelJob", &input).await
        }

        /// Run the `jobs.v1.JobService.GetStatus` query against a workflow by id.
        pub async fn get_status(&self, workflow_id: impl Into<String>) -> Result<JobStatusOutput> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::query_proto_empty::<JobStatusOutput>(&inner, "jobs.v1.JobService.GetStatus").await
        }

        /// Run the `jobs.v1.JobService.Reconfigure` update against a workflow by id.
        pub async fn reconfigure(&self, workflow_id: impl Into<String>, input: ReconfigureInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ReconfigureOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&inner, "jobs.v1.JobService.Reconfigure", &input, wait_policy).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunJobStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl ::std::fmt::Display for RunJobStartOptions {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            let names = self.set_field_names();
            ::std::write!(f, "RunJobStartOptions {{ set: {}/{} [{}] }}", names.len(), Self::FIELD_NAMES.len(), names.join(", "))
        }
    }

    impl RunJobStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        /// Set `workflow_id` to a random UUID via the bridge's `random_workflow_id()`.
        pub fn with_random_workflow_id(mut self) -> Self {
            self.workflow_id = Some(temporal_runtime::random_workflow_id());
            self
        }
        /// Fill `workflow_id` with a random UUID if not already set.
        /// No-op when `workflow_id` is already `Some`.
        pub fn workflow_id_or_random(mut self) -> Self {
            if self.workflow_id.is_none() {
                self.workflow_id = Some(temporal_runtime::random_workflow_id());
            }
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
        /// Apply `other` over self in place. Fields where `other` is `Some` win;
        /// `None` fields in `other` leave self's existing value untouched.
        pub fn merge_in(&mut self, other: Self) {
            if other.workflow_id.is_some() { self.workflow_id = other.workflow_id; }
            if other.task_queue.is_some() { self.task_queue = other.task_queue; }
            if other.id_reuse_policy.is_some() { self.id_reuse_policy = other.id_reuse_policy; }
            if other.id_conflict_policy.is_some() { self.id_conflict_policy = other.id_conflict_policy; }
            if other.execution_timeout.is_some() { self.execution_timeout = other.execution_timeout; }
            if other.run_timeout.is_some() { self.run_timeout = other.run_timeout; }
            if other.task_timeout.is_some() { self.task_timeout = other.task_timeout; }
            if other.enable_eager_workflow_start.is_some() { self.enable_eager_workflow_start = other.enable_eager_workflow_start; }
            if other.retry_policy.is_some() { self.retry_policy = other.retry_policy; }
        }
        pub fn is_empty(&self) -> bool {
            self.workflow_id.is_none()
                && self.task_queue.is_none()
                && self.id_reuse_policy.is_none()
                && self.id_conflict_policy.is_none()
                && self.execution_timeout.is_none()
                && self.run_timeout.is_none()
                && self.task_timeout.is_none()
                && self.enable_eager_workflow_start.is_none()
                && self.retry_policy.is_none()
        }
        /// Names of every field on this options struct, in declaration order.
        /// Stable across re-codegen — see [`Self::set_field_names`] for the per-instance subset.
        pub const FIELD_NAMES: &'static [&'static str] = &[
            "workflow_id",
            "task_queue",
            "id_reuse_policy",
            "id_conflict_policy",
            "execution_timeout",
            "run_timeout",
            "task_timeout",
            "enable_eager_workflow_start",
            "retry_policy",
        ];
        /// Whether the named field is currently `Some`. Returns false for unknown names.
        pub fn has_field_set(&self, name: &str) -> bool {
            match name {
                "workflow_id" => self.workflow_id.is_some(),
                "task_queue" => self.task_queue.is_some(),
                "id_reuse_policy" => self.id_reuse_policy.is_some(),
                "id_conflict_policy" => self.id_conflict_policy.is_some(),
                "execution_timeout" => self.execution_timeout.is_some(),
                "run_timeout" => self.run_timeout.is_some(),
                "task_timeout" => self.task_timeout.is_some(),
                "enable_eager_workflow_start" => self.enable_eager_workflow_start.is_some(),
                "retry_policy" => self.retry_policy.is_some(),
                _ => false,
            }
        }
        /// Reset every field to `None`. Equivalent to `*self = Self::default()`.
        pub fn clear(&mut self) {
            *self = Self::default();
        }
        /// Number of fields with `Some` values. Equivalent to `set_field_names().len()`,
        /// but skips the Vec allocation.
        pub fn set_field_count(&self) -> usize {
            (self.workflow_id.is_some() as usize)
                + (self.task_queue.is_some() as usize)
                + (self.id_reuse_policy.is_some() as usize)
                + (self.id_conflict_policy.is_some() as usize)
                + (self.execution_timeout.is_some() as usize)
                + (self.run_timeout.is_some() as usize)
                + (self.task_timeout.is_some() as usize)
                + (self.enable_eager_workflow_start.is_some() as usize)
                + (self.retry_policy.is_some() as usize)
        }
        /// Names of fields with `Some` values, in declaration order. Empty iff [`Self::is_empty`].
        pub fn set_field_names(&self) -> ::std::vec::Vec<&'static str> {
            let mut out = ::std::vec::Vec::new();
            if self.workflow_id.is_some() { out.push("workflow_id"); }
            if self.task_queue.is_some() { out.push("task_queue"); }
            if self.id_reuse_policy.is_some() { out.push("id_reuse_policy"); }
            if self.id_conflict_policy.is_some() { out.push("id_conflict_policy"); }
            if self.execution_timeout.is_some() { out.push("execution_timeout"); }
            if self.run_timeout.is_some() { out.push("run_timeout"); }
            if self.task_timeout.is_some() { out.push("task_timeout"); }
            if self.enable_eager_workflow_start.is_some() { out.push("enable_eager_workflow_start"); }
            if self.retry_policy.is_some() { out.push("retry_policy"); }
            out
        }
    }

    #[derive(Clone)]
    pub struct RunJobHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for RunJobHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("RunJobHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for RunJobHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl RunJobHandle {
        pub const WORKFLOW_NAME: &'static str = self::RUN_JOB_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::RUN_JOB_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::RUN_JOB_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::RUN_JOB_TASK_QUEUE;
        pub const ID_TEMPLATE: &'static str = self::RUN_JOB_WORKFLOW_ID_TEMPLATE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for RunJobHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::WorkflowHandle> for RunJobHandle {
        fn as_ref(&self) -> &temporal_runtime::WorkflowHandle {
            &self.inner
        }
    }

    impl ::std::cmp::PartialEq for RunJobHandle {
        fn eq(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
                && self.inner.run_id() == other.inner.run_id()
        }
    }
    impl ::std::cmp::Eq for RunJobHandle {}
    impl ::std::hash::Hash for RunJobHandle {
        fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
            self.inner.workflow_id().hash(state);
            self.inner.run_id().hash(state);
        }
    }
    impl ::std::cmp::PartialOrd for RunJobHandle {
        fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
            Some(self.cmp(other))
        }
    }
    impl ::std::cmp::Ord for RunJobHandle {
        fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
            self.inner.workflow_id().cmp(other.inner.workflow_id())
                .then_with(|| self.inner.run_id().cmp(&other.inner.run_id()))
        }
    }

    impl RunJobHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn client(&self) -> &temporal_runtime::TemporalClient {
            self.inner.client()
        }

        pub fn with_run_id(self, run_id: Option<String>) -> Self {
            Self { inner: self.inner.with_run_id(run_id) }
        }

        pub fn without_run_id(self) -> Self {
            self.with_run_id(None)
        }

        pub fn set_run_id(&mut self, run_id: Option<String>) {
            self.inner = self.inner.clone().with_run_id(run_id);
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        /// `true` IFF both handles carry a known run id, the run ids match,
        /// and the workflow ids match. Returns `false` if either side has
        /// no run id (constructed via `<rpc>_handle`) — strict equality requires
        /// proof, and absence of a run id is not proof. Use [`Self::same_workflow_as`]
        /// for the looser "same workflow id" comparison.
        pub fn same_execution_as(&self, other: &Self) -> bool {
            match (self.inner.run_id(), other.inner.run_id()) {
                (Some(a), Some(b)) => a == b && self.inner.workflow_id() == other.inner.workflow_id(),
                _ => false,
            }
        }

        pub fn clone_inner(&self) -> temporal_runtime::WorkflowHandle {
            self.inner.clone()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<JobOutput> {
            temporal_runtime::wait_result_proto::<JobOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

        /// Send the `jobs.v1.JobService.CancelJob` signal.
        pub async fn cancel_job(&self, input: CancelJobInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "jobs.v1.JobService.CancelJob", &input).await
        }

        /// Run the `jobs.v1.JobService.GetStatus` query.
        pub async fn get_status(&self) -> Result<JobStatusOutput> {
            temporal_runtime::query_proto_empty::<JobStatusOutput>(&self.inner, "jobs.v1.JobService.GetStatus").await
        }

        /// Run the `jobs.v1.JobService.Reconfigure` update.
        pub async fn reconfigure(&self, input: ReconfigureInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ReconfigureOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&self.inner, "jobs.v1.JobService.Reconfigure", &input, wait_policy).await
        }

    }

    /// Start `jobs.v1.JobService.RunJob` and atomically deliver the `jobs.v1.JobService.CancelJob` signal.
    pub async fn cancel_job_with_start(
        client: &temporal_runtime::TemporalClient,
        signal_input: CancelJobInput,
        workflow_input: JobInput,
        opts: RunJobStartOptions,
    ) -> Result<RunJobHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            run_job_id(&workflow_input)
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
        let id_reuse_policy = opts.id_reuse_policy;
        let id_conflict_policy = opts.id_conflict_policy;
        let execution_timeout = opts.execution_timeout;
        let run_timeout = opts.run_timeout;
        let task_timeout = opts.task_timeout;
        let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
        let retry_policy = opts.retry_policy;
        let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
        let inner = temporal_runtime::signal_with_start_workflow_proto(
            client,
            RUN_JOB_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "jobs.v1.JobService.CancelJob",
            &signal_input,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok(RunJobHandle { inner })
    }

}
