// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod jobs_v1_job_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::jobs::v1::*;

    impl temporal_runtime::TemporalProtoMessage for CancelJobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.CancelJobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobInput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for JobStatusOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.JobStatusOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureInput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureInput";
    }
    impl temporal_runtime::TemporalProtoMessage for ReconfigureOutput {
        const MESSAGE_TYPE: &'static str = "jobs.v1.ReconfigureOutput";
    }

    pub const RUN_JOB_WORKFLOW_NAME: &str = "jobs.v1.JobService.RunJob";
    pub const RUN_JOB_INPUT_TYPE: &str = "jobs.v1.JobInput";
    pub const RUN_JOB_OUTPUT_TYPE: &str = "jobs.v1.JobOutput";
    pub const RUN_JOB_TASK_QUEUE: &str = "jobs";
    pub const RUN_JOB_WORKFLOW_ID_TEMPLATE: &str = "{{ .Name }}";
    pub const RUN_JOB_ATTACHED_SIGNAL_NAMES: &'static [&'static str] = &["jobs.v1.JobService.CancelJob"];
    pub const RUN_JOB_ATTACHED_QUERY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.GetStatus"];
    pub const RUN_JOB_ATTACHED_UPDATE_NAMES: &'static [&'static str] = &["jobs.v1.JobService.Reconfigure"];

    pub const CANCEL_JOB_SIGNAL_INPUT_TYPE: &str = "jobs.v1.CancelJobInput";
    pub const GET_STATUS_QUERY_INPUT_TYPE: &str = "google.protobuf.Empty";
    pub const GET_STATUS_QUERY_OUTPUT_TYPE: &str = "jobs.v1.JobStatusOutput";
    pub const RECONFIGURE_UPDATE_INPUT_TYPE: &str = "jobs.v1.ReconfigureInput";
    pub const RECONFIGURE_UPDATE_OUTPUT_TYPE: &str = "jobs.v1.ReconfigureOutput";
    pub const PROCESS_CHUNK_ACTIVITY_INPUT_TYPE: &str = "jobs.v1.ChunkInput";
    pub const PROCESS_CHUNK_ACTIVITY_OUTPUT_TYPE: &str = "jobs.v1.ChunkOutput";

    fn run_job_id(input: &JobInput) -> String {
        format!("{}", input.name)
    }

    pub struct JobServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl JobServiceClient {
        pub const PACKAGE: &'static str = "jobs.v1";
        pub const SERVICE_NAME: &'static str = "JobService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "jobs.v1.JobService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["jobs.v1.JobService.RunJob"];
        pub const SIGNAL_NAMES: &'static [&'static str] = &["jobs.v1.JobService.CancelJob"];
        pub const QUERY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.GetStatus"];
        pub const UPDATE_NAMES: &'static [&'static str] = &["jobs.v1.JobService.Reconfigure"];
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["jobs.v1.JobService.ProcessChunk"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `jobs.v1.JobService.RunJob` workflow.
        pub async fn run_job(
            &self,
            input: JobInput,
            opts: RunJobStartOptions,
        ) -> Result<RunJobHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                run_job_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                RUN_JOB_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(RunJobHandle { inner })
        }

        /// Attach to a running `jobs.v1.JobService.RunJob` workflow by id.
        pub fn run_job_handle(&self, workflow_id: impl Into<String>) -> RunJobHandle {
            RunJobHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Send the `jobs.v1.JobService.CancelJob` signal to a workflow by id.
        pub async fn cancel_job(&self, workflow_id: impl Into<String>, input: CancelJobInput) -> Result<()> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::signal_proto(&inner, "jobs.v1.JobService.CancelJob", &input).await
        }

        /// Run the `jobs.v1.JobService.GetStatus` query against a workflow by id.
        pub async fn get_status(&self, workflow_id: impl Into<String>) -> Result<JobStatusOutput> {
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::query_proto_empty::<JobStatusOutput>(&inner, "jobs.v1.JobService.GetStatus").await
        }

        /// Run the `jobs.v1.JobService.Reconfigure` update against a workflow by id.
        pub async fn reconfigure(&self, workflow_id: impl Into<String>, input: ReconfigureInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ReconfigureOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            let inner = temporal_runtime::attach_handle(&self.client, workflow_id.into());
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&inner, "jobs.v1.JobService.Reconfigure", &input, wait_policy).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct RunJobStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl RunJobStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }
    }

    pub struct RunJobHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl RunJobHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<JobOutput> {
            temporal_runtime::wait_result_proto::<JobOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

        /// Send the `jobs.v1.JobService.CancelJob` signal.
        pub async fn cancel_job(&self, input: CancelJobInput) -> Result<()> {
            temporal_runtime::signal_proto(&self.inner, "jobs.v1.JobService.CancelJob", &input).await
        }

        /// Run the `jobs.v1.JobService.GetStatus` query.
        pub async fn get_status(&self) -> Result<JobStatusOutput> {
            temporal_runtime::query_proto_empty::<JobStatusOutput>(&self.inner, "jobs.v1.JobService.GetStatus").await
        }

        /// Run the `jobs.v1.JobService.Reconfigure` update.
        pub async fn reconfigure(&self, input: ReconfigureInput, wait_policy: Option<temporal_runtime::WaitPolicy>) -> Result<ReconfigureOutput> {
            let wait_policy = wait_policy.unwrap_or(temporal_runtime::WaitPolicy::Completed);
            temporal_runtime::update_proto::<ReconfigureInput, ReconfigureOutput>(&self.inner, "jobs.v1.JobService.Reconfigure", &input, wait_policy).await
        }

    }

    /// Start `jobs.v1.JobService.RunJob` and atomically deliver the `jobs.v1.JobService.CancelJob` signal.
    pub async fn cancel_job_with_start(
        client: &temporal_runtime::TemporalClient,
        signal_input: CancelJobInput,
        workflow_input: JobInput,
        opts: RunJobStartOptions,
    ) -> Result<RunJobHandle> {
        let workflow_id = opts.workflow_id.clone().unwrap_or_else(|| {
            run_job_id(&workflow_input)
        });
        let task_queue = opts.task_queue.unwrap_or_else(|| "jobs".to_string());
        let id_reuse_policy = opts.id_reuse_policy;
        let id_conflict_policy = opts.id_conflict_policy;
        let execution_timeout = opts.execution_timeout;
        let run_timeout = opts.run_timeout;
        let task_timeout = opts.task_timeout;
        let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
        let retry_policy = opts.retry_policy;
        let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
        let inner = temporal_runtime::signal_with_start_workflow_proto(
            client,
            RUN_JOB_WORKFLOW_NAME,
            &workflow_id,
            &task_queue,
            &workflow_input,
            "jobs.v1.JobService.CancelJob",
            &signal_input,
            id_reuse_policy,
            execution_timeout,
            run_timeout,
            task_timeout,
        ).await?;
        Ok(RunJobHandle { inner })
    }

}
