// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod solo_v1_solo_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::solo::v1::*;

    impl temporal_runtime::TemporalProtoMessage for WorkInput {
        const MESSAGE_TYPE: &'static str = "solo.v1.WorkInput";
    }
    impl temporal_runtime::TemporalProtoMessage for WorkOutput {
        const MESSAGE_TYPE: &'static str = "solo.v1.WorkOutput";
    }

    pub const DO_WORK_WORKFLOW_NAME: &str = "solo.v1.SoloService.DoWork";
    pub const DO_WORK_INPUT_TYPE: &str = "solo.v1.WorkInput";
    pub const DO_WORK_OUTPUT_TYPE: &str = "solo.v1.WorkOutput";
    pub const DO_WORK_TASK_QUEUE: &str = "solo-tq";

    pub struct SoloServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl SoloServiceClient {
        pub const PACKAGE: &'static str = "solo.v1";
        pub const SERVICE_NAME: &'static str = "SoloService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "solo.v1.SoloService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["solo.v1.SoloService.DoWork"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `solo.v1.SoloService.DoWork` workflow.
        pub async fn do_work(
            &self,
            input: WorkInput,
            opts: DoWorkStartOptions,
        ) -> Result<DoWorkHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "solo-tq".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout.or(Some(Duration::from_secs(3600)));
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                DO_WORK_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(DoWorkHandle { inner })
        }

        /// Attach to a running `solo.v1.SoloService.DoWork` workflow by id.
        pub fn do_work_handle(&self, workflow_id: impl Into<String>) -> DoWorkHandle {
            DoWorkHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct DoWorkStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl DoWorkStartOptions {
        pub fn default_execution_timeout() -> Duration {
            Duration::from_secs(3600)
        }
    }

    pub struct DoWorkHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl DoWorkHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<WorkOutput> {
            temporal_runtime::wait_result_proto::<WorkOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}
