// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod solo_v1_solo_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::solo::v1::*;

    pub const DO_WORK_WORKFLOW_NAME: &str = "solo.v1.SoloService/DoWork";
    pub const DO_WORK_TASK_QUEUE: &str = "solo-tq";

    pub struct SoloServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl SoloServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `solo.v1.SoloService/DoWork` workflow.
        pub async fn do_work(
            &self,
            input: WorkInput,
            opts: DoWorkStartOptions,
        ) -> Result<DoWorkHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "solo-tq".to_string());
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                DO_WORK_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                opts.id_reuse_policy,
                opts.execution_timeout,
                opts.run_timeout,
                opts.task_timeout,
            ).await?;
            Ok(DoWorkHandle { inner })
        }

        /// Attach to a running `solo.v1.SoloService/DoWork` workflow by id.
        pub fn do_work_handle(&self, workflow_id: impl Into<String>) -> DoWorkHandle {
            DoWorkHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct DoWorkStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
    }

    impl DoWorkStartOptions {
        pub fn default_execution_timeout() -> Duration {
            Duration::from_secs(3600)
        }
    }

    pub struct DoWorkHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl DoWorkHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<WorkOutput> {
            temporal_runtime::wait_result_proto::<WorkOutput>(&self.inner).await
        }

    }

}
