// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod workeract_v1_activity_worker_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::workeract::v1::*;

    impl temporal_runtime::TemporalProtoMessage for FetchInput {
        const MESSAGE_TYPE: &'static str = "workeract.v1.FetchInput";
    }
    impl temporal_runtime::TemporalProtoMessage for FetchOutput {
        const MESSAGE_TYPE: &'static str = "workeract.v1.FetchOutput";
    }

    pub struct ActivityWorkerServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ActivityWorkerServiceClient {
        pub const ACTIVITY_NAMES: &'static [&'static str] = &["workeract.v1.ActivityWorkerService.Fetch", "workeract.v1.ActivityWorkerService.Ping"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

    }


    // ── Activities ────────────────────────────────────────────
    // Phase 2 (activities=true): typed trait + name consts. Wire to
    // your worker via temporalio-sdk's #[activities] macro;
    // see temporal-proto-runtime-bridge README for the adapter pattern.

    pub const FETCH_ACTIVITY_NAME: &str = "workeract.v1.ActivityWorkerService.Fetch";
    pub const PING_ACTIVITY_NAME: &str = "workeract.v1.ActivityWorkerService.Ping";

    pub struct FetchActivity;
    impl temporal_runtime::worker::ActivityDefinition for FetchActivity {
        type Input = temporal_runtime::TypedProtoMessage<FetchInput>;
        type Output = temporal_runtime::TypedProtoMessage<FetchOutput>;
        fn name() -> &'static str { FETCH_ACTIVITY_NAME }
    }
    pub async fn execute_fetch<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: FetchInput,
        opts: temporal_runtime::worker::ActivityOptions,
    ) -> ::std::result::Result<FetchOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_activity(FetchActivity, input, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }
    pub async fn execute_fetch_local<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        input: FetchInput,
        opts: temporal_runtime::worker::LocalActivityOptions,
    ) -> ::std::result::Result<FetchOutput, temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_local_activity(FetchActivity, input, opts).await.map(temporal_runtime::TypedProtoMessage::into_inner)
    }
    pub struct PingActivity;
    impl temporal_runtime::worker::ActivityDefinition for PingActivity {
        type Input = temporal_runtime::TypedProtoMessage<temporal_runtime::ProtoEmpty>;
        type Output = temporal_runtime::TypedProtoMessage<temporal_runtime::ProtoEmpty>;
        fn name() -> &'static str { PING_ACTIVITY_NAME }
    }
    pub async fn execute_ping<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        opts: temporal_runtime::worker::ActivityOptions,
    ) -> ::std::result::Result<(), temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_activity(PingActivity, temporal_runtime::ProtoEmpty {}, opts).await.map(|_| ())
    }
    pub async fn execute_ping_local<W>(
        ctx: &temporal_runtime::worker::WorkflowContext<W>,
        opts: temporal_runtime::worker::LocalActivityOptions,
    ) -> ::std::result::Result<(), temporal_runtime::worker::ActivityExecutionError> {
        ctx.start_local_activity(PingActivity, temporal_runtime::ProtoEmpty {}, opts).await.map(|_| ())
    }

    pub trait ActivityWorkerServiceActivities: Send + Sync + 'static {
        fn fetch(&self, ctx: temporal_runtime::ActivityContext, input: FetchInput) -> impl ::std::future::Future<Output = Result<FetchOutput>> + Send;
        fn ping(&self, ctx: temporal_runtime::ActivityContext, input: ()) -> impl ::std::future::Future<Output = Result<()>> + Send;
    }

    pub fn register_activity_worker_service_activities<I>(worker: &mut temporal_runtime::worker::Worker, impl_: I) -> &mut temporal_runtime::worker::Worker
    where
        I: ActivityWorkerServiceActivities + temporal_runtime::worker::ActivityImplementer,
    {
        worker.register_activities(impl_)
    }
}
