// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod cli_v1_report_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    impl temporal_runtime::TemporalProtoMessage for GenerateInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateInput";
    }
    impl temporal_runtime::TemporalProtoMessage for GenerateOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for InternalInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.InternalInput";
    }
    impl temporal_runtime::TemporalProtoMessage for InternalOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.InternalOutput";
    }

    pub const GENERATE_WORKFLOW_NAME: &str = "cli.v1.ReportService.Generate";
    pub const GENERATE_INPUT_TYPE: &str = "cli.v1.GenerateInput";
    pub const GENERATE_OUTPUT_TYPE: &str = "cli.v1.GenerateOutput";
    pub const GENERATE_TASK_QUEUE: &str = "reports";
    pub const GENERATE_WORKFLOW_ID_TEMPLATE: &str = "gen-{{ .Name }}";
    pub const INTERNAL_WORKFLOW_NAME: &str = "cli.v1.ReportService.Internal";
    pub const INTERNAL_INPUT_TYPE: &str = "cli.v1.InternalInput";
    pub const INTERNAL_OUTPUT_TYPE: &str = "cli.v1.InternalOutput";
    pub const INTERNAL_TASK_QUEUE: &str = "reports";

    fn generate_id(input: &GenerateInput) -> String {
        let id = format!("gen-{}", input.name);
        assert!(!id.is_empty(), "workflow id template `gen-{{}}` resolved to an empty string at runtime — check that every referenced input field has a non-empty value");
        if let Some(bad) = id.chars().find(|c| c.is_control()) {
            panic!("workflow id template `gen-{{}}` resolved to a value containing control character {:?} at runtime — check the referenced input fields for embedded newlines / tabs", bad);
        }
        id
    }

    #[derive(Clone)]
    pub struct ReportServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for ReportServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("ReportServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for ReportServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl ReportServiceClient {
        pub const PACKAGE: &'static str = "cli.v1";
        pub const SERVICE_NAME: &'static str = "ReportService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "cli.v1.ReportService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["cli.v1.ReportService.Generate", "cli.v1.ReportService.Internal"];

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn random_workflow_id() -> String {
            temporal_runtime::random_workflow_id()
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for ReportServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ReportServiceClient {
        /// Start a new `cli.v1.ReportService.Generate` workflow.
        pub async fn generate(
            &self,
            input: GenerateInput,
            opts: GenerateStartOptions,
        ) -> Result<GenerateHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                generate_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                GENERATE_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(GenerateHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        pub fn generate_handle(&self, workflow_id: impl Into<String>) -> GenerateHandle {
            GenerateHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Start a new `cli.v1.ReportService.Internal` workflow.
        pub async fn internal(
            &self,
            input: InternalInput,
            opts: InternalStartOptions,
        ) -> Result<InternalHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                INTERNAL_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(InternalHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Internal` workflow by id.
        pub fn internal_handle(&self, workflow_id: impl Into<String>) -> InternalHandle {
            InternalHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct GenerateStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl GenerateStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
    }

    #[derive(Clone)]
    pub struct GenerateHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for GenerateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("GenerateHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for GenerateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl GenerateHandle {
        pub const WORKFLOW_NAME: &'static str = self::GENERATE_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::GENERATE_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::GENERATE_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::GENERATE_TASK_QUEUE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for GenerateHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl GenerateHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<GenerateOutput> {
            temporal_runtime::wait_result_proto::<GenerateOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct InternalStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl InternalStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
    }

    #[derive(Clone)]
    pub struct InternalHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for InternalHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("InternalHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for InternalHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl InternalHandle {
        pub const WORKFLOW_NAME: &'static str = self::INTERNAL_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::INTERNAL_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::INTERNAL_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::INTERNAL_TASK_QUEUE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for InternalHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl InternalHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<InternalOutput> {
            temporal_runtime::wait_result_proto::<InternalOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}

/// Phase 4.0 CLI scaffold. clap-derive parser structure; dispatch
/// is consumer-supplied until Phase 4.1 lands the `Cli::run` impl.
#[allow(clippy::all, unused_imports, dead_code)]
pub mod report_service_cli {
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    #[derive(Debug, temporal_runtime::clap::Parser)]
    #[command(name = "report_service", about = "Generated Temporal CLI for cli.v1.ReportService")]
    pub struct Cli {
        #[command(subcommand)]
        pub command: Command,
    }

    #[derive(Debug, temporal_runtime::clap::Subcommand)]
    pub enum Command {
        /// Start a new `cli.v1.ReportService.Generate` workflow.
        StartGenerate(StartGenerateArgs),
        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        AttachGenerate(AttachGenerateArgs),
        /// Request cooperative cancellation of a running `cli.v1.ReportService.Generate` workflow by id.
        CancelGenerate(CancelGenerateArgs),
        /// Terminate a running `cli.v1.ReportService.Generate` workflow by id.
        TerminateGenerate(TerminateGenerateArgs),
    }

    impl Cli {
        /// Dispatch the parsed command against `client`.
        ///
        /// `read_input` decodes the `--input-file` JSON/bytes-on-disk into the typed proto
        /// message. The plugin stays agnostic to the encoding (pbjson, serde, raw prost
        /// bytes, …) — the consumer wires their preferred decode strategy. The closure
        /// receives `(path, fully_qualified_message_type)` so it can switch on the type
        /// when a service has heterogeneous workflow inputs.
        pub async fn run_with<F, Fut>(
            self,
            client: &super::cli_v1_report_service_temporal::ReportServiceClient,
            mut read_input: F,
        ) -> ::std::result::Result<(), ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>
        where
            F: FnMut(&::std::path::Path, &'static str) -> Fut,
            Fut: ::std::future::Future<Output = ::std::result::Result<::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>, ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>>,
        {
            match self.command {
                Command::StartGenerate(args) => {
                    let dyn_input = read_input(&args.input_file, "cli.v1.GenerateInput").await?;
                    let input: GenerateInput = *dyn_input.downcast::<GenerateInput>()
                        .map_err(|_| ::std::format!("read_input returned the wrong type for cli.v1.GenerateInput"))?;
                    let opts = super::cli_v1_report_service_temporal::GenerateStartOptions { workflow_id: args.workflow_id, ..::std::default::Default::default() };
                    let handle = client.generate(input, opts).await?;
                    ::std::println!("started {}: workflow_id={}", super::cli_v1_report_service_temporal::GENERATE_WORKFLOW_NAME, handle.workflow_id());
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::AttachGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    ::std::println!("attached: workflow_id={}", args.workflow_id);
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::CancelGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    handle.cancel_workflow(&args.reason).await?;
                    ::std::println!("cancel requested: workflow_id={}", args.workflow_id);
                }
                Command::TerminateGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    handle.terminate_workflow(&args.reason).await?;
                    ::std::println!("terminated: workflow_id={}", args.workflow_id);
                }
            }
            Ok(())
        }
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct StartGenerateArgs {
        /// Path to a JSON file containing the workflow input.
        /// Format: prost-json (matching pbjson) of `cli.v1.GenerateInput`.
        #[arg(long)]
        pub input_file: ::std::path::PathBuf,
        /// Override the workflow id (otherwise derived from the proto template / random).
        #[arg(long)]
        pub workflow_id: Option<String>,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct AttachGenerateArgs {
        /// Workflow id to attach to.
        pub workflow_id: String,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct CancelGenerateArgs {
        /// Workflow id to cancel.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct TerminateGenerateArgs {
        /// Workflow id to terminate.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

}
