// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
pub mod cli_v1_report_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    impl temporal_runtime::TemporalProtoMessage for GenerateInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateInput";
    }
    impl temporal_runtime::TemporalProtoMessage for GenerateOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for InternalInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.InternalInput";
    }
    impl temporal_runtime::TemporalProtoMessage for InternalOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.InternalOutput";
    }

    pub const GENERATE_WORKFLOW_NAME: &str = "cli.v1.ReportService.Generate";
    pub const GENERATE_TASK_QUEUE: &str = "reports";
    pub const INTERNAL_WORKFLOW_NAME: &str = "cli.v1.ReportService.Internal";
    pub const INTERNAL_TASK_QUEUE: &str = "reports";

    fn generate_id(input: &GenerateInput) -> String {
        format!("gen-{}", input.name)
    }

    pub struct ReportServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ReportServiceClient {
        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        /// Start a new `cli.v1.ReportService.Generate` workflow.
        pub async fn generate(
            &self,
            input: GenerateInput,
            opts: GenerateStartOptions,
        ) -> Result<GenerateHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                generate_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                GENERATE_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(GenerateHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        pub fn generate_handle(&self, workflow_id: impl Into<String>) -> GenerateHandle {
            GenerateHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Start a new `cli.v1.ReportService.Internal` workflow.
        pub async fn internal(
            &self,
            input: InternalInput,
            opts: InternalStartOptions,
        ) -> Result<InternalHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                INTERNAL_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(InternalHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Internal` workflow by id.
        pub fn internal_handle(&self, workflow_id: impl Into<String>) -> InternalHandle {
            InternalHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct GenerateStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    pub struct GenerateHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl GenerateHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<GenerateOutput> {
            temporal_runtime::wait_result_proto::<GenerateOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct InternalStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    pub struct InternalHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl InternalHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<InternalOutput> {
            temporal_runtime::wait_result_proto::<InternalOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}

/// Phase 4.0 CLI scaffold. clap-derive parser structure; dispatch
/// is consumer-supplied until Phase 4.1 lands the `Cli::run` impl.
#[allow(clippy::all, unused_imports, dead_code)]
pub mod report_service_cli {
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    #[derive(temporal_runtime::clap::Parser)]
    #[command(name = "report_service", about = "Generated Temporal CLI for cli.v1.ReportService")]
    pub struct Cli {
        #[command(subcommand)]
        pub command: Command,
    }

    #[derive(temporal_runtime::clap::Subcommand)]
    pub enum Command {
        /// Start a new `cli.v1.ReportService.Generate` workflow.
        StartGenerate(StartGenerateArgs),
        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        AttachGenerate(AttachGenerateArgs),
    }

    impl Cli {
        /// Dispatch the parsed command against `client`.
        ///
        /// `read_input` decodes the `--input-file` JSON/bytes-on-disk into the typed proto
        /// message. The plugin stays agnostic to the encoding (pbjson, serde, raw prost
        /// bytes, …) — the consumer wires their preferred decode strategy. The closure
        /// receives `(path, fully_qualified_message_type)` so it can switch on the type
        /// when a service has heterogeneous workflow inputs.
        pub async fn run_with<F, Fut>(
            self,
            client: &super::cli_v1_report_service_temporal::ReportServiceClient,
            mut read_input: F,
        ) -> ::std::result::Result<(), ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>
        where
            F: FnMut(&::std::path::Path, &'static str) -> Fut,
            Fut: ::std::future::Future<Output = ::std::result::Result<::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>, ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>>,
        {
            match self.command {
                Command::StartGenerate(args) => {
                    let dyn_input = read_input(&args.input_file, "cli.v1.GenerateInput").await?;
                    let input: GenerateInput = *dyn_input.downcast::<GenerateInput>()
                        .map_err(|_| ::std::format!("read_input returned the wrong type for cli.v1.GenerateInput"))?;
                    let opts = super::cli_v1_report_service_temporal::GenerateStartOptions { workflow_id: args.workflow_id, ..::std::default::Default::default() };
                    let handle = client.generate(input, opts).await?;
                    ::std::println!("started {}: workflow_id={}", super::cli_v1_report_service_temporal::GENERATE_WORKFLOW_NAME, handle.workflow_id());
                    if args.wait { let _ = handle.result().await?; }
                }
                Command::AttachGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    ::std::println!("attached: workflow_id={}", args.workflow_id);
                    if args.wait { let _ = handle.result().await?; }
                }
            }
            Ok(())
        }
    }

    #[derive(temporal_runtime::clap::Args)]
    pub struct StartGenerateArgs {
        /// Path to a JSON file containing the workflow input.
        /// Format: prost-json (matching pbjson) of `cli.v1.GenerateInput`.
        #[arg(long)]
        pub input_file: ::std::path::PathBuf,
        /// Override the workflow id (otherwise derived from the proto template / random).
        #[arg(long)]
        pub workflow_id: Option<String>,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(temporal_runtime::clap::Args)]
    pub struct AttachGenerateArgs {
        /// Workflow id to attach to.
        pub workflow_id: String,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

}
