// Code generated by protoc-gen-rust-temporal. DO NOT EDIT.
// source: input.proto

#[allow(clippy::all, unused_imports, dead_code)]
/// Generated Temporal client + worker surface for `cli.v1.ReportService`.
///
/// Construct a typed client with [`ReportServiceClient::connect`] (or
/// [`ReportServiceClient::new`] from an existing `TemporalClient`).
/// Each workflow rpc gets a typed start method, an attach helper, and a
/// `<Workflow>Handle` wrapper exposing signal / query / update / cancel
/// / terminate / result paths typed against the proto.
///
/// Identity consts (`PACKAGE`, `SERVICE_NAME`, `FULLY_QUALIFIED_SERVICE_NAME`,
/// `SOURCE_FILE`, `GENERATED_BY_PLUGIN_VERSION`) on the client and per-rpc
/// `<RPC>_*` name / type consts at module scope let tooling enumerate the wire
/// surface without descriptor-pool
/// round-trips.
pub mod cli_v1_report_service_temporal {
    use anyhow::Result;
    use std::time::Duration;
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    impl temporal_runtime::TemporalProtoMessage for AggregateInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.AggregateInput";
    }
    impl temporal_runtime::TemporalProtoMessage for AggregateOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.AggregateOutput";
    }
    impl temporal_runtime::TemporalProtoMessage for GenerateInput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateInput";
    }
    impl temporal_runtime::TemporalProtoMessage for GenerateOutput {
        const MESSAGE_TYPE: &'static str = "cli.v1.GenerateOutput";
    }

    pub const PACKAGE: &str = "cli.v1";
    pub const SERVICE_NAME: &str = "ReportService";
    pub const FULLY_QUALIFIED_SERVICE_NAME: &str = "cli.v1.ReportService";
    pub const SOURCE_FILE: &str = "input.proto";
    pub const CLUDDEN_SCHEMA_DIGEST: &str = "buf.build/cludden/protoc-gen-go-temporal:6d988a28838c46ebb99eaa042cf2a607";
    pub const WIRE_FORMAT_VERSION: &str = "v1";
    pub const GENERATE_WORKFLOW_NAME: &str = "cli.v1.ReportService.Generate";
    pub const GENERATE_INPUT_TYPE: &str = "cli.v1.GenerateInput";
    pub const GENERATE_OUTPUT_TYPE: &str = "cli.v1.GenerateOutput";
    pub const GENERATE_TASK_QUEUE: &str = "reports";
    pub const GENERATE_WORKFLOW_ID_TEMPLATE: &str = "gen-{{ .Name }}";
    pub const AGGREGATE_WORKFLOW_NAME: &str = "cli.v1.ReportService.Aggregate";
    pub const AGGREGATE_INPUT_TYPE: &str = "cli.v1.AggregateInput";
    pub const AGGREGATE_OUTPUT_TYPE: &str = "cli.v1.AggregateOutput";
    pub const AGGREGATE_TASK_QUEUE: &str = "reports";

    fn generate_id(input: &GenerateInput) -> String {
        let id = format!("gen-{}", input.name);
        assert!(!id.is_empty(), "workflow id template `gen-{{}}` resolved to an empty string at runtime — check that every referenced input field has a non-empty value");
        if let Some(bad) = id.chars().find(|c| c.is_control()) {
            panic!("workflow id template `gen-{{}}` resolved to a value containing control character {:?} at runtime — check the referenced input fields for embedded newlines / tabs", bad);
        }
        id
    }

    #[derive(Clone)]
    pub struct ReportServiceClient {
        client: temporal_runtime::TemporalClient,
    }

    impl ::std::fmt::Debug for ReportServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("ReportServiceClient")
                .field("package", &Self::PACKAGE)
                .field("service", &Self::SERVICE_NAME)
                .field("plugin_version", &Self::GENERATED_BY_PLUGIN_VERSION)
                .finish_non_exhaustive()
        }
    }

    impl ::std::fmt::Display for ReportServiceClient {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.write_str(Self::FULLY_QUALIFIED_SERVICE_NAME)
        }
    }

    impl ReportServiceClient {
        pub const PACKAGE: &'static str = "cli.v1";
        pub const SERVICE_NAME: &'static str = "ReportService";
        pub const FULLY_QUALIFIED_SERVICE_NAME: &'static str = "cli.v1.ReportService";
        pub const SOURCE_FILE: &'static str = "input.proto";
        pub const GENERATED_BY_PLUGIN_VERSION: &'static str = "protoc-gen-rust-temporal 0.1.1";
        pub const WORKFLOW_NAMES: &'static [&'static str] = &["cli.v1.ReportService.Generate", "cli.v1.ReportService.Aggregate"];
        pub const ALL_HANDLER_NAMES: &'static [&'static str] = &["cli.v1.ReportService.Generate", "cli.v1.ReportService.Aggregate"];
        pub const HANDLER_COUNT: usize = Self::ALL_HANDLER_NAMES.len();
        pub const TASK_QUEUES: &'static [&'static str] = &["reports"];

        /// Look up which handler kind a registered name belongs to.
        /// Returns `"workflow"` / `"signal"` / `"query"` / `"update"` / `"activity"`,
        /// or `None` if the name doesn't match any handler this service registers.
        pub fn lookup_handler_kind(name: &str) -> Option<&'static str> {
            if Self::WORKFLOW_NAMES.contains(&name) { return Some("workflow"); }
            None
        }

        pub fn new(client: temporal_runtime::TemporalClient) -> Self {
            Self { client }
        }

        pub async fn connect(url: &str, namespace: &str) -> Result<Self> {
            let client = temporal_runtime::connect(url, namespace).await?;
            Ok(Self::new(client))
        }

        pub fn inner(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }

        pub fn namespace(&self) -> String {
            self.client.namespace()
        }

        pub fn random_workflow_id() -> String {
            temporal_runtime::random_workflow_id()
        }

        pub fn into_inner(self) -> temporal_runtime::TemporalClient {
            self.client
        }

        pub fn clone_inner(&self) -> temporal_runtime::TemporalClient {
            self.client.clone()
        }

    }

    impl ::std::convert::From<temporal_runtime::TemporalClient> for ReportServiceClient {
        fn from(client: temporal_runtime::TemporalClient) -> Self {
            Self::new(client)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::TemporalClient> for ReportServiceClient {
        fn as_ref(&self) -> &temporal_runtime::TemporalClient {
            &self.client
        }
    }

    impl ReportServiceClient {
        /// Start a new `cli.v1.ReportService.Generate` workflow.
        pub async fn generate(
            &self,
            input: GenerateInput,
            opts: GenerateStartOptions,
        ) -> Result<GenerateHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                generate_id(&input)
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                GENERATE_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(GenerateHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        pub fn generate_handle(&self, workflow_id: impl Into<String>) -> GenerateHandle {
            GenerateHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

        /// Start a new `cli.v1.ReportService.Aggregate` workflow.
        pub async fn aggregate(
            &self,
            input: AggregateInput,
            opts: AggregateStartOptions,
        ) -> Result<AggregateHandle> {
            let workflow_id = opts.workflow_id.unwrap_or_else(|| {
                temporal_runtime::random_workflow_id()
            });
            let task_queue = opts.task_queue.unwrap_or_else(|| "reports".to_string());
            let id_reuse_policy = opts.id_reuse_policy;
            let id_conflict_policy = opts.id_conflict_policy;
            let execution_timeout = opts.execution_timeout;
            let run_timeout = opts.run_timeout;
            let task_timeout = opts.task_timeout;
            let enable_eager_workflow_start = opts.enable_eager_workflow_start.unwrap_or(false);
            let retry_policy = opts.retry_policy;
            let search_attributes = ::std::option::Option::<::std::collections::HashMap<::std::string::String, temporal_runtime::ProtoPayload>>::None;
            let inner = temporal_runtime::start_workflow_proto(
                &self.client,
                AGGREGATE_WORKFLOW_NAME,
                &workflow_id,
                &task_queue,
                &input,
                id_reuse_policy,
                id_conflict_policy,
                execution_timeout,
                run_timeout,
                task_timeout,
                enable_eager_workflow_start,
                retry_policy,
                search_attributes,
            ).await?;
            Ok(AggregateHandle { inner })
        }

        /// Attach to a running `cli.v1.ReportService.Aggregate` workflow by id.
        pub fn aggregate_handle(&self, workflow_id: impl Into<String>) -> AggregateHandle {
            AggregateHandle {
                inner: temporal_runtime::attach_handle(&self.client, workflow_id.into()),
            }
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct GenerateStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl GenerateStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
        pub fn is_empty(&self) -> bool {
            self.workflow_id.is_none()
                && self.task_queue.is_none()
                && self.id_reuse_policy.is_none()
                && self.id_conflict_policy.is_none()
                && self.execution_timeout.is_none()
                && self.run_timeout.is_none()
                && self.task_timeout.is_none()
                && self.enable_eager_workflow_start.is_none()
                && self.retry_policy.is_none()
        }
        /// Reset every field to `None`. Equivalent to `*self = Self::default()`.
        pub fn clear(&mut self) {
            *self = Self::default();
        }
        /// Names of fields with `Some` values, in declaration order. Empty iff [`Self::is_empty`].
        pub fn set_field_names(&self) -> ::std::vec::Vec<&'static str> {
            let mut out = ::std::vec::Vec::new();
            if self.workflow_id.is_some() { out.push("workflow_id"); }
            if self.task_queue.is_some() { out.push("task_queue"); }
            if self.id_reuse_policy.is_some() { out.push("id_reuse_policy"); }
            if self.id_conflict_policy.is_some() { out.push("id_conflict_policy"); }
            if self.execution_timeout.is_some() { out.push("execution_timeout"); }
            if self.run_timeout.is_some() { out.push("run_timeout"); }
            if self.task_timeout.is_some() { out.push("task_timeout"); }
            if self.enable_eager_workflow_start.is_some() { out.push("enable_eager_workflow_start"); }
            if self.retry_policy.is_some() { out.push("retry_policy"); }
            out
        }
    }

    #[derive(Clone)]
    pub struct GenerateHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for GenerateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("GenerateHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for GenerateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl GenerateHandle {
        pub const WORKFLOW_NAME: &'static str = self::GENERATE_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::GENERATE_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::GENERATE_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::GENERATE_TASK_QUEUE;
        pub const ID_TEMPLATE: &'static str = self::GENERATE_WORKFLOW_ID_TEMPLATE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for GenerateHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::WorkflowHandle> for GenerateHandle {
        fn as_ref(&self) -> &temporal_runtime::WorkflowHandle {
            &self.inner
        }
    }

    impl ::std::cmp::PartialEq for GenerateHandle {
        fn eq(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
                && self.inner.run_id() == other.inner.run_id()
        }
    }
    impl ::std::cmp::Eq for GenerateHandle {}
    impl ::std::hash::Hash for GenerateHandle {
        fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
            self.inner.workflow_id().hash(state);
            self.inner.run_id().hash(state);
        }
    }
    impl ::std::cmp::PartialOrd for GenerateHandle {
        fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
            Some(self.cmp(other))
        }
    }
    impl ::std::cmp::Ord for GenerateHandle {
        fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
            self.inner.workflow_id().cmp(other.inner.workflow_id())
                .then_with(|| self.inner.run_id().cmp(&other.inner.run_id()))
        }
    }

    impl GenerateHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn client(&self) -> &temporal_runtime::TemporalClient {
            self.inner.client()
        }

        pub fn with_run_id(self, run_id: Option<String>) -> Self {
            Self { inner: self.inner.with_run_id(run_id) }
        }

        pub fn without_run_id(self) -> Self {
            self.with_run_id(None)
        }

        pub fn set_run_id(&mut self, run_id: Option<String>) {
            self.inner = self.inner.clone().with_run_id(run_id);
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        /// `true` IFF both handles carry a known run id, the run ids match,
        /// and the workflow ids match. Returns `false` if either side has
        /// no run id (constructed via `<rpc>_handle`) — strict equality requires
        /// proof, and absence of a run id is not proof. Use [`Self::same_workflow_as`]
        /// for the looser "same workflow id" comparison.
        pub fn same_execution_as(&self, other: &Self) -> bool {
            match (self.inner.run_id(), other.inner.run_id()) {
                (Some(a), Some(b)) => a == b && self.inner.workflow_id() == other.inner.workflow_id(),
                _ => false,
            }
        }

        pub fn clone_inner(&self) -> temporal_runtime::WorkflowHandle {
            self.inner.clone()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<GenerateOutput> {
            temporal_runtime::wait_result_proto::<GenerateOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

    #[derive(Debug, Default, Clone)]
    pub struct AggregateStartOptions {
        pub workflow_id: Option<String>,
        pub task_queue: Option<String>,
        pub id_reuse_policy: Option<temporal_runtime::WorkflowIdReusePolicy>,
        pub id_conflict_policy: Option<temporal_runtime::WorkflowIdConflictPolicy>,
        pub execution_timeout: Option<Duration>,
        pub run_timeout: Option<Duration>,
        pub task_timeout: Option<Duration>,
        pub enable_eager_workflow_start: Option<bool>,
        pub retry_policy: Option<temporal_runtime::RetryPolicy>,
    }

    impl AggregateStartOptions {
        pub fn with_workflow_id(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.workflow_id = Some(v.into());
            self
        }
        pub fn with_task_queue(mut self, v: impl ::std::convert::Into<String>) -> Self {
            self.task_queue = Some(v.into());
            self
        }
        pub fn with_id_reuse_policy(mut self, v: temporal_runtime::WorkflowIdReusePolicy) -> Self {
            self.id_reuse_policy = Some(v);
            self
        }
        pub fn with_id_conflict_policy(mut self, v: temporal_runtime::WorkflowIdConflictPolicy) -> Self {
            self.id_conflict_policy = Some(v);
            self
        }
        pub fn with_execution_timeout(mut self, v: Duration) -> Self {
            self.execution_timeout = Some(v);
            self
        }
        pub fn with_run_timeout(mut self, v: Duration) -> Self {
            self.run_timeout = Some(v);
            self
        }
        pub fn with_task_timeout(mut self, v: Duration) -> Self {
            self.task_timeout = Some(v);
            self
        }
        pub fn with_enable_eager_workflow_start(mut self, v: bool) -> Self {
            self.enable_eager_workflow_start = Some(v);
            self
        }
        pub fn with_retry_policy(mut self, v: temporal_runtime::RetryPolicy) -> Self {
            self.retry_policy = Some(v);
            self
        }

        /// Layer `other` over `self`, with `other`'s fields winning.
        /// Lets callers fold env-driven overrides over a base config without
        /// re-deriving each field. Per-field: `other.<f>.or(self.<f>)`.
        pub fn merge(mut self, other: Self) -> Self {
            self.workflow_id = other.workflow_id.or(self.workflow_id);
            self.task_queue = other.task_queue.or(self.task_queue);
            self.id_reuse_policy = other.id_reuse_policy.or(self.id_reuse_policy);
            self.id_conflict_policy = other.id_conflict_policy.or(self.id_conflict_policy);
            self.execution_timeout = other.execution_timeout.or(self.execution_timeout);
            self.run_timeout = other.run_timeout.or(self.run_timeout);
            self.task_timeout = other.task_timeout.or(self.task_timeout);
            self.enable_eager_workflow_start = other.enable_eager_workflow_start.or(self.enable_eager_workflow_start);
            self.retry_policy = other.retry_policy.or(self.retry_policy);
            self
        }
        pub fn is_empty(&self) -> bool {
            self.workflow_id.is_none()
                && self.task_queue.is_none()
                && self.id_reuse_policy.is_none()
                && self.id_conflict_policy.is_none()
                && self.execution_timeout.is_none()
                && self.run_timeout.is_none()
                && self.task_timeout.is_none()
                && self.enable_eager_workflow_start.is_none()
                && self.retry_policy.is_none()
        }
        /// Reset every field to `None`. Equivalent to `*self = Self::default()`.
        pub fn clear(&mut self) {
            *self = Self::default();
        }
        /// Names of fields with `Some` values, in declaration order. Empty iff [`Self::is_empty`].
        pub fn set_field_names(&self) -> ::std::vec::Vec<&'static str> {
            let mut out = ::std::vec::Vec::new();
            if self.workflow_id.is_some() { out.push("workflow_id"); }
            if self.task_queue.is_some() { out.push("task_queue"); }
            if self.id_reuse_policy.is_some() { out.push("id_reuse_policy"); }
            if self.id_conflict_policy.is_some() { out.push("id_conflict_policy"); }
            if self.execution_timeout.is_some() { out.push("execution_timeout"); }
            if self.run_timeout.is_some() { out.push("run_timeout"); }
            if self.task_timeout.is_some() { out.push("task_timeout"); }
            if self.enable_eager_workflow_start.is_some() { out.push("enable_eager_workflow_start"); }
            if self.retry_policy.is_some() { out.push("retry_policy"); }
            out
        }
    }

    #[derive(Clone)]
    pub struct AggregateHandle {
        inner: temporal_runtime::WorkflowHandle,
    }

    impl ::std::fmt::Debug for AggregateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            f.debug_struct("AggregateHandle")
                .field("workflow_name", &Self::WORKFLOW_NAME)
                .field("workflow_id", &self.inner.workflow_id())
                .field("run_id", &self.inner.run_id())
                .finish()
        }
    }

    impl ::std::fmt::Display for AggregateHandle {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            write!(f, "{}({})", Self::WORKFLOW_NAME, self.inner.workflow_id())
        }
    }

    impl AggregateHandle {
        pub const WORKFLOW_NAME: &'static str = self::AGGREGATE_WORKFLOW_NAME;
        pub const INPUT_TYPE: &'static str = self::AGGREGATE_INPUT_TYPE;
        pub const OUTPUT_TYPE: &'static str = self::AGGREGATE_OUTPUT_TYPE;
        pub const TASK_QUEUE: &'static str = self::AGGREGATE_TASK_QUEUE;

        pub fn from_inner(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self { inner }
        }

    }

    impl ::std::convert::From<temporal_runtime::WorkflowHandle> for AggregateHandle {
        fn from(inner: temporal_runtime::WorkflowHandle) -> Self {
            Self::from_inner(inner)
        }
    }

    impl ::std::convert::AsRef<temporal_runtime::WorkflowHandle> for AggregateHandle {
        fn as_ref(&self) -> &temporal_runtime::WorkflowHandle {
            &self.inner
        }
    }

    impl ::std::cmp::PartialEq for AggregateHandle {
        fn eq(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
                && self.inner.run_id() == other.inner.run_id()
        }
    }
    impl ::std::cmp::Eq for AggregateHandle {}
    impl ::std::hash::Hash for AggregateHandle {
        fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
            self.inner.workflow_id().hash(state);
            self.inner.run_id().hash(state);
        }
    }
    impl ::std::cmp::PartialOrd for AggregateHandle {
        fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
            Some(self.cmp(other))
        }
    }
    impl ::std::cmp::Ord for AggregateHandle {
        fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
            self.inner.workflow_id().cmp(other.inner.workflow_id())
                .then_with(|| self.inner.run_id().cmp(&other.inner.run_id()))
        }
    }

    impl AggregateHandle {
        pub fn workflow_id(&self) -> &str {
            self.inner.workflow_id()
        }

        pub fn workflow_id_owned(&self) -> String {
            self.inner.workflow_id().to_string()
        }

        pub fn client(&self) -> &temporal_runtime::TemporalClient {
            self.inner.client()
        }

        pub fn with_run_id(self, run_id: Option<String>) -> Self {
            Self { inner: self.inner.with_run_id(run_id) }
        }

        pub fn without_run_id(self) -> Self {
            self.with_run_id(None)
        }

        pub fn set_run_id(&mut self, run_id: Option<String>) {
            self.inner = self.inner.clone().with_run_id(run_id);
        }

        pub fn same_workflow_as(&self, other: &Self) -> bool {
            self.inner.workflow_id() == other.inner.workflow_id()
        }

        /// `true` IFF both handles carry a known run id, the run ids match,
        /// and the workflow ids match. Returns `false` if either side has
        /// no run id (constructed via `<rpc>_handle`) — strict equality requires
        /// proof, and absence of a run id is not proof. Use [`Self::same_workflow_as`]
        /// for the looser "same workflow id" comparison.
        pub fn same_execution_as(&self, other: &Self) -> bool {
            match (self.inner.run_id(), other.inner.run_id()) {
                (Some(a), Some(b)) => a == b && self.inner.workflow_id() == other.inner.workflow_id(),
                _ => false,
            }
        }

        pub fn clone_inner(&self) -> temporal_runtime::WorkflowHandle {
            self.inner.clone()
        }

        pub fn into_inner(self) -> temporal_runtime::WorkflowHandle {
            self.inner
        }

        /// The execution's run id, if known. `None` for handles created
        /// via `<rpc>_handle(workflow_id)` (the consumer didn't supply one);
        /// `Some(...)` for handles returned by the start path.
        pub fn run_id(&self) -> Option<&str> {
            self.inner.run_id()
        }

        pub fn run_id_owned(&self) -> Option<String> {
            self.inner.run_id().map(String::from)
        }

        /// `true` if this handle has a known run id (started via the typed start
        /// path); `false` if it was constructed via `<rpc>_handle(workflow_id)`.
        pub fn has_run_id(&self) -> bool {
            self.inner.run_id().is_some()
        }

        /// Wait for the workflow to complete and return its output.
        pub async fn result(&self) -> Result<AggregateOutput> {
            temporal_runtime::wait_result_proto::<AggregateOutput>(&self.inner).await
        }

        /// Request cooperative cancellation. `reason` is recorded in event history.
        pub async fn cancel_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::cancel_workflow(&self.inner, reason).await
        }

        /// Terminate the workflow — hard kill, no cancel handler runs.
        pub async fn terminate_workflow(&self, reason: &str) -> Result<()> {
            temporal_runtime::terminate_workflow(&self.inner, reason).await
        }

    }

}

/// Phase 4.0 CLI scaffold. clap-derive parser structure; dispatch
/// is consumer-supplied until Phase 4.1 lands the `Cli::run` impl.
#[allow(clippy::all, unused_imports, dead_code)]
pub mod report_service_cli {
    use crate::temporal_runtime;
    use crate::cli::v1::*;

    #[derive(Debug, temporal_runtime::clap::Parser)]
    #[command(name = "report_service", about = "Generated Temporal CLI for cli.v1.ReportService")]
    pub struct Cli {
        #[command(subcommand)]
        pub command: Command,
    }

    #[derive(Debug, temporal_runtime::clap::Subcommand)]
    pub enum Command {
        /// Start a new `cli.v1.ReportService.Generate` workflow.
        StartGenerate(StartGenerateArgs),
        /// Attach to a running `cli.v1.ReportService.Generate` workflow by id.
        AttachGenerate(AttachGenerateArgs),
        /// Request cooperative cancellation of a running `cli.v1.ReportService.Generate` workflow by id.
        CancelGenerate(CancelGenerateArgs),
        /// Terminate a running `cli.v1.ReportService.Generate` workflow by id.
        TerminateGenerate(TerminateGenerateArgs),
        /// Start a new `cli.v1.ReportService.Aggregate` workflow.
        StartAggregate(StartAggregateArgs),
        /// Attach to a running `cli.v1.ReportService.Aggregate` workflow by id.
        AttachAggregate(AttachAggregateArgs),
        /// Request cooperative cancellation of a running `cli.v1.ReportService.Aggregate` workflow by id.
        CancelAggregate(CancelAggregateArgs),
        /// Terminate a running `cli.v1.ReportService.Aggregate` workflow by id.
        TerminateAggregate(TerminateAggregateArgs),
    }

    impl Command {
        /// Registered (cross-language) name of the handler this subcommand targets.
        /// Workflow verbs (Start/Attach/Cancel/Terminate) share the workflow name;
        /// Signal/Query/Update variants return their own handler's name.
        pub fn handler_name(&self) -> &'static str {
            match self {
                Self::StartGenerate(_) => "cli.v1.ReportService.Generate",
                Self::AttachGenerate(_) => "cli.v1.ReportService.Generate",
                Self::CancelGenerate(_) => "cli.v1.ReportService.Generate",
                Self::TerminateGenerate(_) => "cli.v1.ReportService.Generate",
                Self::StartAggregate(_) => "cli.v1.ReportService.Aggregate",
                Self::AttachAggregate(_) => "cli.v1.ReportService.Aggregate",
                Self::CancelAggregate(_) => "cli.v1.ReportService.Aggregate",
                Self::TerminateAggregate(_) => "cli.v1.ReportService.Aggregate",
            }
        }
        /// Action verb of this subcommand: one of `start` / `attach` / `cancel`
        /// / `terminate` / `signal` / `query` / `update`. Pairs with [`Self::handler_name`]
        /// for `(verb, handler)` dispatch telemetry.
        pub fn verb(&self) -> &'static str {
            match self {
                Self::StartGenerate(_) => "start",
                Self::AttachGenerate(_) => "attach",
                Self::CancelGenerate(_) => "cancel",
                Self::TerminateGenerate(_) => "terminate",
                Self::StartAggregate(_) => "start",
                Self::AttachAggregate(_) => "attach",
                Self::CancelAggregate(_) => "cancel",
                Self::TerminateAggregate(_) => "terminate",
            }
        }
        /// Workflow id this subcommand targets, when known.
        /// `Start*` variants return the user's `--workflow-id` override (`None` means
        /// the runtime will synthesize one); all other variants always return `Some`.
        pub fn workflow_id(&self) -> Option<&str> {
            match self {
                Self::StartGenerate(args) => args.workflow_id.as_deref(),
                Self::AttachGenerate(args) => Some(&args.workflow_id),
                Self::CancelGenerate(args) => Some(&args.workflow_id),
                Self::TerminateGenerate(args) => Some(&args.workflow_id),
                Self::StartAggregate(args) => args.workflow_id.as_deref(),
                Self::AttachAggregate(args) => Some(&args.workflow_id),
                Self::CancelAggregate(args) => Some(&args.workflow_id),
                Self::TerminateAggregate(args) => Some(&args.workflow_id),
            }
        }
        /// Whether the `--wait` flag was set on this subcommand.
        /// `Some(true)` / `Some(false)` for `Start*` and `Attach*` (which model
        /// the flag); `None` for all other verbs (which don't).
        pub fn wait(&self) -> Option<bool> {
            match self {
                Self::StartGenerate(args) => Some(args.wait),
                Self::AttachGenerate(args) => Some(args.wait),
                Self::StartAggregate(args) => Some(args.wait),
                Self::AttachAggregate(args) => Some(args.wait),
                _ => None,
            }
        }
        /// Cancellation/termination reason, when this subcommand carries one.
        /// `Some` for `Cancel*` and `Terminate*` (which model `--reason`, default "");
        /// `None` for all other verbs (which don't have the field).
        pub fn reason(&self) -> Option<&str> {
            match self {
                Self::CancelGenerate(args) => Some(args.reason.as_str()),
                Self::TerminateGenerate(args) => Some(args.reason.as_str()),
                Self::CancelAggregate(args) => Some(args.reason.as_str()),
                Self::TerminateAggregate(args) => Some(args.reason.as_str()),
                _ => None,
            }
        }
    }

    impl Cli {
        /// Dispatch the parsed command against `client`.
        ///
        /// `read_input` decodes the `--input-file` JSON/bytes-on-disk into the typed proto
        /// message. The plugin stays agnostic to the encoding (pbjson, serde, raw prost
        /// bytes, …) — the consumer wires their preferred decode strategy. The closure
        /// receives `(path, fully_qualified_message_type)` so it can switch on the type
        /// when a service has heterogeneous workflow inputs.
        pub async fn run_with<F, Fut>(
            self,
            client: &super::cli_v1_report_service_temporal::ReportServiceClient,
            mut read_input: F,
        ) -> ::std::result::Result<(), ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>
        where
            F: FnMut(&::std::path::Path, &'static str) -> Fut,
            Fut: ::std::future::Future<Output = ::std::result::Result<::std::boxed::Box<dyn ::std::any::Any + ::std::marker::Send>, ::std::boxed::Box<dyn ::std::error::Error + Send + Sync>>>,
        {
            match self.command {
                Command::StartGenerate(args) => {
                    let dyn_input = read_input(&args.input_file, "cli.v1.GenerateInput").await?;
                    let input: GenerateInput = *dyn_input.downcast::<GenerateInput>()
                        .map_err(|_| ::std::format!("read_input returned the wrong type for cli.v1.GenerateInput"))?;
                    let opts = super::cli_v1_report_service_temporal::GenerateStartOptions { workflow_id: args.workflow_id, ..::std::default::Default::default() };
                    let handle = client.generate(input, opts).await?;
                    ::std::println!("started {}: workflow_id={}", super::cli_v1_report_service_temporal::GENERATE_WORKFLOW_NAME, handle.workflow_id());
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::AttachGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    ::std::println!("attached: workflow_id={}", args.workflow_id);
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::CancelGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    handle.cancel_workflow(&args.reason).await?;
                    ::std::println!("cancel requested: workflow_id={}", args.workflow_id);
                }
                Command::TerminateGenerate(args) => {
                    let handle = client.generate_handle(args.workflow_id.clone());
                    handle.terminate_workflow(&args.reason).await?;
                    ::std::println!("terminated: workflow_id={}", args.workflow_id);
                }
                Command::StartAggregate(args) => {
                    let dyn_input = read_input(&args.input_file, "cli.v1.AggregateInput").await?;
                    let input: AggregateInput = *dyn_input.downcast::<AggregateInput>()
                        .map_err(|_| ::std::format!("read_input returned the wrong type for cli.v1.AggregateInput"))?;
                    let opts = super::cli_v1_report_service_temporal::AggregateStartOptions { workflow_id: args.workflow_id, ..::std::default::Default::default() };
                    let handle = client.aggregate(input, opts).await?;
                    ::std::println!("started {}: workflow_id={}", super::cli_v1_report_service_temporal::AGGREGATE_WORKFLOW_NAME, handle.workflow_id());
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::AttachAggregate(args) => {
                    let handle = client.aggregate_handle(args.workflow_id.clone());
                    ::std::println!("attached: workflow_id={}", args.workflow_id);
                    if args.wait { let out = handle.result().await?; ::std::println!("result={:?}", out); }
                }
                Command::CancelAggregate(args) => {
                    let handle = client.aggregate_handle(args.workflow_id.clone());
                    handle.cancel_workflow(&args.reason).await?;
                    ::std::println!("cancel requested: workflow_id={}", args.workflow_id);
                }
                Command::TerminateAggregate(args) => {
                    let handle = client.aggregate_handle(args.workflow_id.clone());
                    handle.terminate_workflow(&args.reason).await?;
                    ::std::println!("terminated: workflow_id={}", args.workflow_id);
                }
            }
            Ok(())
        }
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct StartGenerateArgs {
        /// Path to a JSON file containing the workflow input.
        /// Format: prost-json (matching pbjson) of `cli.v1.GenerateInput`.
        #[arg(long)]
        pub input_file: ::std::path::PathBuf,
        /// Override the workflow id (otherwise derived from the proto template / random).
        #[arg(long)]
        pub workflow_id: Option<String>,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct AttachGenerateArgs {
        /// Workflow id to attach to.
        pub workflow_id: String,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct CancelGenerateArgs {
        /// Workflow id to cancel.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct TerminateGenerateArgs {
        /// Workflow id to terminate.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct StartAggregateArgs {
        /// Path to a JSON file containing the workflow input.
        /// Format: prost-json (matching pbjson) of `cli.v1.AggregateInput`.
        #[arg(long)]
        pub input_file: ::std::path::PathBuf,
        /// Override the workflow id (otherwise derived from the proto template / random).
        #[arg(long)]
        pub workflow_id: Option<String>,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct AttachAggregateArgs {
        /// Workflow id to attach to.
        pub workflow_id: String,
        /// Wait for the workflow to complete and print its result.
        #[arg(long)]
        pub wait: bool,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct CancelAggregateArgs {
        /// Workflow id to cancel.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

    #[derive(Debug, Clone, temporal_runtime::clap::Args)]
    pub struct TerminateAggregateArgs {
        /// Workflow id to terminate.
        pub workflow_id: String,
        /// Reason recorded in event history. Defaults to an empty string.
        #[arg(long, default_value = "")]
        pub reason: String,
    }

}
